---
title: "Worst is Wrong and Boring"
subtitle: "An eye roll at tedious bigots"
date: "2023-09-19"
categories: [poetry, english]
format: html
---

*First published on Medium for Bouncin' and Behavin' Poems ([link to original post](https://medium.com/the-bouncin-and-behavin-poetry-society/the-worst-is-wrong-and-boring-e0e581ef69c3?sk=cd3f4438608bfd155280f92251f2e18c)).*

The worst is wrong and boring.\
Tell me the sky isn’t blue\
And what that really means to you\
Why it matters so\
That I should listen, want to ask you, want to know

You say the sexes are clearly two.\
Wrong. But boring? Up to you.\
Does the certainty comfort you\
Does conforming give meaning to you\
Does demeaning invigorate you\
Does envy motivate you\
Contempt contort you into shapes that hurt and yet — you like it, don’t you?

Tell me what’s wrong. Tell me true. Tell me what hurts so I may give it to you new.

Give me your cries. Honest. Scream!\
But — I’m begging — make it interesting.

Tell me the sky isn’t blue.\
Take me on a journey\
By the hand\
To the grass you’re really pointing to

And we may lie on it\
Face up (or down, up to you)\
And be curious together\
Interesting\
Alive

And by then the sky may be dark but there will be stars, a moon or two.\
And if it feels like up is down, down is up, the moon is green and the stars are swirling still on invisible ripples but loud\
Tell me what it means to occupy this center\
To walk through the world confused, uncertain\
Whether anyone sees what you see, hears what you fear, feels what you scream
