{
  "hash": "17311a3cbc2945c7bb65f6d275e81228",
  "result": {
    "markdown": "---\ntitle: \"Adventures in mediation analysis with weighted GLMs (temporary title)\"\nsubtitle: \"subtitle TBD\"\nauthor: Vasco Brazão, Priya Devendran\ndate: \"2023\"\ncategories: [statistics, mediation, survey, glm]\ndraft: true\nexecute: \n  warning: false\nformat:\n  html:\n    code-fold: show\n---\n\n\nThis blogpost documents the challenges we faced when attempting to run a mediation analysis using the `mediation` package with a binomial mediator and outcome while incorporating sampling weights into the analysis with the help of the `survey` package. Issues and solutions are summarized below. Click the issue number to jump straight to the relevant section of the post.\n\n::: callout-note\n## Issues and solutions: summary\n\n[Issue 1: Correctly applying the Fragile Families weights]\n\n**Description**: We need to specify jackknife estimation of standard errors for `survey` to properly handle our replicate weights.\n\n**Solution**: Besides specifying the `weights` and `repweights` arguments, we also have to specify `combined_weights = TRUE`, `type = \"JKn\"`, `scales = 1`, `rscales = 1`, and `mse = TRUE`.\n\n[Issue 2: Mediation with \"multiple-trial binomial mediator\" runs for weighted but not for unweighted models?]\n\n**Description**: When using multiple-trial binomial GLMs for the mediator and outcome models, `mediate()` complains: \"`weights on outcome and mediator models not identical`\".\n\n**Solution**: The problem occurs when we specify the GLMs with a proportion as the outcome and the total number of trials given in the `weights` argument, if the number of trials is different for both models. We can overcome this by specifying the outcome as `cbind(successes, failures)`. However, according to the package documentation, `mediate()` should not accept multiple-trial binomial mediators in the first place, leaving us with some doubts about whether all the estimates are calculated correctly in this case.\n\n[Issue 3: Using a binary mediator and a binomial outcome --- works with cbind(successes, failures) but not with proportion as outcome and weights argument specified](#issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified)\n\n**Description**: When using a single trial binomial GLM for the mediator model and a multiple-trial binomial GLM for the outcome model, `mediate()` complains: \"`weights on outcome and mediator models not identical`\".\n\n**Solution**: As in Issue 2, the issue is solved by using the `cbind(successes, failures)` specification for the outcome model.\n\n[Issue 4: Ordinal mediator and binomial outcome don't work together]\n\n**Description**: When the mediator model is ordinal (fit with `MASS::polr()`, `mediate()` will not work with a binomial outcome model either way it's specified.\n\n**Solution**: No solution was found, other than using an ordinal mediator model with a binary outcome model.\n\n[Issue 5: mediate() is not compatible with svyolr() models]\n\n**Description**: It seems that `mediate()` simply won't work with models fit with `survey::svyolr()`.\n\n**Solution**: No solution was found.\n\n[Issue 6: Options and choices to boot --- To robustSE or not to robustSE?]\n\n**Description**: `mediate()` can work via boostrap or quasi-Bayesian approximation, and has an option to calculate \"robust standard errors\" for the latter. Which options work with survey-weighted GLMs?\n\n**Solution**: Bootstrapping should probably not be used. `robustSE` should be set to `FALSE`. If `marginaleffects` is used for comparisons, `vcov` should be set to `vcov(model)` or `NULL`, as the `sandwich` package does not correctly compute robust standard errors for models fit with `survey`.\n\n[Issue 7: Boundaries of the confidence intervals are rounded differently]\n\n**Description**: When you apply `summary()` to an object produced by `mediate()`, the upper bound of the confidence intervals is rounded to only two decimal places, whereas there are more decimal places for the lower bound.\n\n**Solution**: We can modify the function `print.summary.mediate()` to get around this problem, although the current solution then messes with how the p-values are reported.\n:::\n\n# Background\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the packages we will use\nlibrary(tidyverse)\nlibrary(here)\nlibrary(mediation)\nlibrary(survey)\nlibrary(srvyr)\nlibrary(gt)\nlibrary(MASS)\nlibrary(marginaleffects)\n\n\n# directory for the post (to change once post goes live)\npost_folder <- \"wip_mediation-weighted-glm\"\n\n# number of simulations for mediation analysis\nn_sims <- 1000\n```\n:::\n\n\nAs part of a research program seeking to better understand intimate partner violence (IPV) through an intersectional lens, we wanted to use the [Future of Families & Child Wellbeing Study](https://ffcws.princeton.edu/)[^1] dataset to run a mediation analysis. The data come from a survey with a complex design, and baseline and replicate weights are provided for each participant in the \"national\" sample.[^2] These weights should allow us to make estimates nationally representative. Our mediator and outcome variables could reasonably be construed as binomial outcomes, and this was our preferred approach to fitting the necessary models. However, we encountered several difficulties along the way, and attempt to document and make sense of them here.\n\n[^1]: Previously called the \"Fragile Families and Child Wellbeing Study\".\n\n[^2]: For more information about the weights, have a look at the [methodology document linked here](https://ffcws.princeton.edu/sites/g/files/toruqf4356/files/ff_const_wgts.pdf).\n\nFor demonstrative purposes we created a synthetic dataset using the `synthpop` package. This dataset mirrors the characteristics of our data without it being possible to identify any real individuals from it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get synthetic dataset\ndat <- readRDS(here::here(\"posts\", post_folder, \"data_reduced_synth.RDS\")) |> \n  # create other variables we will need\n  dplyr::mutate(\n    informal_support_prop = informal_support/3,\n    informal_support_max = 3,\n    informal_support_binary = ifelse(informal_support == 3, 1, 0),\n    informal_support_ordinal = forcats::as_factor(informal_support) |> \n      forcats::fct_relevel(\"0\", \"1\", \"2\", \"3\"),\n    IPV_prop = IPV/24,\n    IPV_max = 25,\n    IPV_binary = ifelse(IPV > 0, 1, 0),\n    IPV_ordinal = forcats::as_factor(IPV) |> \n      forcats::fct_expand(\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\", \"12\", \"13\", \"14\", \"15\", \"16\", \"17\", \"18\", \"19\", \"20\", \"21\", \"22\", \"23\", \"24\") |> \n      forcats::fct_relevel(\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\", \"12\", \"13\", \"14\", \"15\", \"16\", \"17\", \"18\", \"19\", \"20\", \"21\", \"22\", \"23\", \"24\")\n  ) |> \n  dplyr::relocate(\n    !dplyr::starts_with(\"m1\"),\n    .before = \"m1natwt\"\n  )\n```\n:::\n\n\nWe have three variables that will be used for mediation, `race` (\"White\" or \"Black\"), `informal_support` (an integer from 0 to 3), and `IPV` (an integer from 0 to 24). We manually create `_prop` and `_max` variables for informal support and IPV, so that we can use the proportion as an outcome in our GLMs and use the `weights` argument to specify the number of trials. We also create `informal_support_binary`, which classifies women as having high access to informal support (takes the value 1) when they score 3 out of 3, and low access (takes the value 0) when they score less than 3, as well as `IPV_binary`, which classifies women as having experienced some form of IPV (takes the value 1) if they score more than 0 and as not having experienced IPV (takes the value 0) if they score exactly 0. These binarized variables will become useful later on. Finally, we create the ordered factors `informal_support_ordinal` and `IPV_ordinal` to be used in ordinal models later on.\n\nEach person also has a baseline weight, `m1natwt`, and 33 replicate weights, `m1natwt_rep1` and so on. Behold:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(dat) |> \n  gt::gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"rqxbngkzij\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#rqxbngkzij .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rqxbngkzij .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rqxbngkzij .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rqxbngkzij .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rqxbngkzij .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rqxbngkzij .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rqxbngkzij .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rqxbngkzij .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rqxbngkzij .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rqxbngkzij .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rqxbngkzij .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rqxbngkzij .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rqxbngkzij .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rqxbngkzij .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rqxbngkzij .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rqxbngkzij .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rqxbngkzij .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rqxbngkzij .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rqxbngkzij .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rqxbngkzij .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rqxbngkzij .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rqxbngkzij .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rqxbngkzij .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rqxbngkzij .gt_left {\n  text-align: left;\n}\n\n#rqxbngkzij .gt_center {\n  text-align: center;\n}\n\n#rqxbngkzij .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rqxbngkzij .gt_font_normal {\n  font-weight: normal;\n}\n\n#rqxbngkzij .gt_font_bold {\n  font-weight: bold;\n}\n\n#rqxbngkzij .gt_font_italic {\n  font-style: italic;\n}\n\n#rqxbngkzij .gt_super {\n  font-size: 65%;\n}\n\n#rqxbngkzij .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#rqxbngkzij .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rqxbngkzij .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rqxbngkzij .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rqxbngkzij .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rqxbngkzij .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rqxbngkzij .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"race\">race</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"informal_support\">informal_support</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IPV\">IPV</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"informal_support_prop\">informal_support_prop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"informal_support_max\">informal_support_max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"informal_support_binary\">informal_support_binary</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"informal_support_ordinal\">informal_support_ordinal</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IPV_prop\">IPV_prop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IPV_max\">IPV_max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IPV_binary\">IPV_binary</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IPV_ordinal\">IPV_ordinal</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt\">m1natwt</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep1\">m1natwt_rep1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep2\">m1natwt_rep2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep3\">m1natwt_rep3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep4\">m1natwt_rep4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep5\">m1natwt_rep5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep6\">m1natwt_rep6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep7\">m1natwt_rep7</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep8\">m1natwt_rep8</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep9\">m1natwt_rep9</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep10\">m1natwt_rep10</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep11\">m1natwt_rep11</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep12\">m1natwt_rep12</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep13\">m1natwt_rep13</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep14\">m1natwt_rep14</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep15\">m1natwt_rep15</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep16\">m1natwt_rep16</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep17\">m1natwt_rep17</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep18\">m1natwt_rep18</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep19\">m1natwt_rep19</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep20\">m1natwt_rep20</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep21\">m1natwt_rep21</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep22\">m1natwt_rep22</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep23\">m1natwt_rep23</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep24\">m1natwt_rep24</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep25\">m1natwt_rep25</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep26\">m1natwt_rep26</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep27\">m1natwt_rep27</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep28\">m1natwt_rep28</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep29\">m1natwt_rep29</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep30\">m1natwt_rep30</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep31\">m1natwt_rep31</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep32\">m1natwt_rep32</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"m1natwt_rep33\">m1natwt_rep33</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"race\" class=\"gt_row gt_center\">Black</td>\n<td headers=\"informal_support\" class=\"gt_row gt_right\">3</td>\n<td headers=\"IPV\" class=\"gt_row gt_right\">18</td>\n<td headers=\"informal_support_prop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_max\" class=\"gt_row gt_right\">3</td>\n<td headers=\"informal_support_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_ordinal\" class=\"gt_row gt_center\">3</td>\n<td headers=\"IPV_prop\" class=\"gt_row gt_right\">0.75000000</td>\n<td headers=\"IPV_max\" class=\"gt_row gt_right\">25</td>\n<td headers=\"IPV_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"IPV_ordinal\" class=\"gt_row gt_center\">18</td>\n<td headers=\"m1natwt\" class=\"gt_row gt_right\">41.13614</td>\n<td headers=\"m1natwt_rep1\" class=\"gt_row gt_right\">37.85516</td>\n<td headers=\"m1natwt_rep2\" class=\"gt_row gt_right\">41.24734</td>\n<td headers=\"m1natwt_rep3\" class=\"gt_row gt_right\">42.44724</td>\n<td headers=\"m1natwt_rep4\" class=\"gt_row gt_right\">44.39487</td>\n<td headers=\"m1natwt_rep5\" class=\"gt_row gt_right\">43.73881</td>\n<td headers=\"m1natwt_rep6\" class=\"gt_row gt_right\">44.45506</td>\n<td headers=\"m1natwt_rep7\" class=\"gt_row gt_right\">40.57142</td>\n<td headers=\"m1natwt_rep8\" class=\"gt_row gt_right\">40.78370</td>\n<td headers=\"m1natwt_rep9\" class=\"gt_row gt_right\">41.43095</td>\n<td headers=\"m1natwt_rep10\" class=\"gt_row gt_right\">34.34425</td>\n<td headers=\"m1natwt_rep11\" class=\"gt_row gt_right\">44.46661</td>\n<td headers=\"m1natwt_rep12\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep13\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep14\" class=\"gt_row gt_right\">37.94593</td>\n<td headers=\"m1natwt_rep15\" class=\"gt_row gt_right\">41.50523</td>\n<td headers=\"m1natwt_rep16\" class=\"gt_row gt_right\">43.69954</td>\n<td headers=\"m1natwt_rep17\" class=\"gt_row gt_right\">41.31135</td>\n<td headers=\"m1natwt_rep18\" class=\"gt_row gt_right\">39.22795</td>\n<td headers=\"m1natwt_rep19\" class=\"gt_row gt_right\">42.50257</td>\n<td headers=\"m1natwt_rep20\" class=\"gt_row gt_right\">42.02170</td>\n<td headers=\"m1natwt_rep21\" class=\"gt_row gt_right\">46.58911</td>\n<td headers=\"m1natwt_rep22\" class=\"gt_row gt_right\">41.82341</td>\n<td headers=\"m1natwt_rep23\" class=\"gt_row gt_right\">45.53830</td>\n<td headers=\"m1natwt_rep24\" class=\"gt_row gt_right\">42.27204</td>\n<td headers=\"m1natwt_rep25\" class=\"gt_row gt_right\">42.28968</td>\n<td headers=\"m1natwt_rep26\" class=\"gt_row gt_right\">43.25393</td>\n<td headers=\"m1natwt_rep27\" class=\"gt_row gt_right\">40.67841</td>\n<td headers=\"m1natwt_rep28\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep29\" class=\"gt_row gt_right\">42.64928</td>\n<td headers=\"m1natwt_rep30\" class=\"gt_row gt_right\">42.28931</td>\n<td headers=\"m1natwt_rep31\" class=\"gt_row gt_right\">42.82657</td>\n<td headers=\"m1natwt_rep32\" class=\"gt_row gt_right\">43.13633</td>\n<td headers=\"m1natwt_rep33\" class=\"gt_row gt_right\">44.10038</td></tr>\n    <tr><td headers=\"race\" class=\"gt_row gt_center\">Black</td>\n<td headers=\"informal_support\" class=\"gt_row gt_right\">3</td>\n<td headers=\"IPV\" class=\"gt_row gt_right\">4</td>\n<td headers=\"informal_support_prop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_max\" class=\"gt_row gt_right\">3</td>\n<td headers=\"informal_support_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_ordinal\" class=\"gt_row gt_center\">3</td>\n<td headers=\"IPV_prop\" class=\"gt_row gt_right\">0.16666667</td>\n<td headers=\"IPV_max\" class=\"gt_row gt_right\">25</td>\n<td headers=\"IPV_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"IPV_ordinal\" class=\"gt_row gt_center\">4</td>\n<td headers=\"m1natwt\" class=\"gt_row gt_right\">19.97570</td>\n<td headers=\"m1natwt_rep1\" class=\"gt_row gt_right\">22.96839</td>\n<td headers=\"m1natwt_rep2\" class=\"gt_row gt_right\">20.49259</td>\n<td headers=\"m1natwt_rep3\" class=\"gt_row gt_right\">20.21818</td>\n<td headers=\"m1natwt_rep4\" class=\"gt_row gt_right\">21.76786</td>\n<td headers=\"m1natwt_rep5\" class=\"gt_row gt_right\">20.79500</td>\n<td headers=\"m1natwt_rep6\" class=\"gt_row gt_right\">20.41886</td>\n<td headers=\"m1natwt_rep7\" class=\"gt_row gt_right\">21.54646</td>\n<td headers=\"m1natwt_rep8\" class=\"gt_row gt_right\">19.36423</td>\n<td headers=\"m1natwt_rep9\" class=\"gt_row gt_right\">19.80069</td>\n<td headers=\"m1natwt_rep10\" class=\"gt_row gt_right\">19.47093</td>\n<td headers=\"m1natwt_rep11\" class=\"gt_row gt_right\">19.58197</td>\n<td headers=\"m1natwt_rep12\" class=\"gt_row gt_right\">20.42065</td>\n<td headers=\"m1natwt_rep13\" class=\"gt_row gt_right\">19.78305</td>\n<td headers=\"m1natwt_rep14\" class=\"gt_row gt_right\">20.23575</td>\n<td headers=\"m1natwt_rep15\" class=\"gt_row gt_right\">21.36903</td>\n<td headers=\"m1natwt_rep16\" class=\"gt_row gt_right\">20.48008</td>\n<td headers=\"m1natwt_rep17\" class=\"gt_row gt_right\">20.91415</td>\n<td headers=\"m1natwt_rep18\" class=\"gt_row gt_right\">20.30889</td>\n<td headers=\"m1natwt_rep19\" class=\"gt_row gt_right\">21.36875</td>\n<td headers=\"m1natwt_rep20\" class=\"gt_row gt_right\">19.87386</td>\n<td headers=\"m1natwt_rep21\" class=\"gt_row gt_right\">21.06265</td>\n<td headers=\"m1natwt_rep22\" class=\"gt_row gt_right\">20.41880</td>\n<td headers=\"m1natwt_rep23\" class=\"gt_row gt_right\">23.67257</td>\n<td headers=\"m1natwt_rep24\" class=\"gt_row gt_right\">20.81135</td>\n<td headers=\"m1natwt_rep25\" class=\"gt_row gt_right\">21.42606</td>\n<td headers=\"m1natwt_rep26\" class=\"gt_row gt_right\">21.32215</td>\n<td headers=\"m1natwt_rep27\" class=\"gt_row gt_right\">19.58435</td>\n<td headers=\"m1natwt_rep28\" class=\"gt_row gt_right\">20.62730</td>\n<td headers=\"m1natwt_rep29\" class=\"gt_row gt_right\">21.86095</td>\n<td headers=\"m1natwt_rep30\" class=\"gt_row gt_right\">20.91533</td>\n<td headers=\"m1natwt_rep31\" class=\"gt_row gt_right\">20.08396</td>\n<td headers=\"m1natwt_rep32\" class=\"gt_row gt_right\">20.84812</td>\n<td headers=\"m1natwt_rep33\" class=\"gt_row gt_right\">20.38860</td></tr>\n    <tr><td headers=\"race\" class=\"gt_row gt_center\">Black</td>\n<td headers=\"informal_support\" class=\"gt_row gt_right\">3</td>\n<td headers=\"IPV\" class=\"gt_row gt_right\">0</td>\n<td headers=\"informal_support_prop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_max\" class=\"gt_row gt_right\">3</td>\n<td headers=\"informal_support_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_ordinal\" class=\"gt_row gt_center\">3</td>\n<td headers=\"IPV_prop\" class=\"gt_row gt_right\">0.00000000</td>\n<td headers=\"IPV_max\" class=\"gt_row gt_right\">25</td>\n<td headers=\"IPV_binary\" class=\"gt_row gt_right\">0</td>\n<td headers=\"IPV_ordinal\" class=\"gt_row gt_center\">0</td>\n<td headers=\"m1natwt\" class=\"gt_row gt_right\">12.24003</td>\n<td headers=\"m1natwt_rep1\" class=\"gt_row gt_right\">12.68406</td>\n<td headers=\"m1natwt_rep2\" class=\"gt_row gt_right\">11.59396</td>\n<td headers=\"m1natwt_rep3\" class=\"gt_row gt_right\">12.10748</td>\n<td headers=\"m1natwt_rep4\" class=\"gt_row gt_right\">12.00069</td>\n<td headers=\"m1natwt_rep5\" class=\"gt_row gt_right\">13.18730</td>\n<td headers=\"m1natwt_rep6\" class=\"gt_row gt_right\">11.88648</td>\n<td headers=\"m1natwt_rep7\" class=\"gt_row gt_right\">12.80008</td>\n<td headers=\"m1natwt_rep8\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep9\" class=\"gt_row gt_right\">12.55978</td>\n<td headers=\"m1natwt_rep10\" class=\"gt_row gt_right\">11.89597</td>\n<td headers=\"m1natwt_rep11\" class=\"gt_row gt_right\">12.56892</td>\n<td headers=\"m1natwt_rep12\" class=\"gt_row gt_right\">12.57526</td>\n<td headers=\"m1natwt_rep13\" class=\"gt_row gt_right\">12.47836</td>\n<td headers=\"m1natwt_rep14\" class=\"gt_row gt_right\">11.46254</td>\n<td headers=\"m1natwt_rep15\" class=\"gt_row gt_right\">12.59188</td>\n<td headers=\"m1natwt_rep16\" class=\"gt_row gt_right\">12.65551</td>\n<td headers=\"m1natwt_rep17\" class=\"gt_row gt_right\">11.98436</td>\n<td headers=\"m1natwt_rep18\" class=\"gt_row gt_right\">12.49196</td>\n<td headers=\"m1natwt_rep19\" class=\"gt_row gt_right\">12.09257</td>\n<td headers=\"m1natwt_rep20\" class=\"gt_row gt_right\">13.70510</td>\n<td headers=\"m1natwt_rep21\" class=\"gt_row gt_right\">13.18920</td>\n<td headers=\"m1natwt_rep22\" class=\"gt_row gt_right\">12.23701</td>\n<td headers=\"m1natwt_rep23\" class=\"gt_row gt_right\">12.59980</td>\n<td headers=\"m1natwt_rep24\" class=\"gt_row gt_right\">12.74326</td>\n<td headers=\"m1natwt_rep25\" class=\"gt_row gt_right\">13.78494</td>\n<td headers=\"m1natwt_rep26\" class=\"gt_row gt_right\">12.39277</td>\n<td headers=\"m1natwt_rep27\" class=\"gt_row gt_right\">13.22096</td>\n<td headers=\"m1natwt_rep28\" class=\"gt_row gt_right\">11.71815</td>\n<td headers=\"m1natwt_rep29\" class=\"gt_row gt_right\">13.12761</td>\n<td headers=\"m1natwt_rep30\" class=\"gt_row gt_right\">12.33747</td>\n<td headers=\"m1natwt_rep31\" class=\"gt_row gt_right\">11.22335</td>\n<td headers=\"m1natwt_rep32\" class=\"gt_row gt_right\">12.79405</td>\n<td headers=\"m1natwt_rep33\" class=\"gt_row gt_right\">13.22079</td></tr>\n    <tr><td headers=\"race\" class=\"gt_row gt_center\">Black</td>\n<td headers=\"informal_support\" class=\"gt_row gt_right\">3</td>\n<td headers=\"IPV\" class=\"gt_row gt_right\">0</td>\n<td headers=\"informal_support_prop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_max\" class=\"gt_row gt_right\">3</td>\n<td headers=\"informal_support_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_ordinal\" class=\"gt_row gt_center\">3</td>\n<td headers=\"IPV_prop\" class=\"gt_row gt_right\">0.00000000</td>\n<td headers=\"IPV_max\" class=\"gt_row gt_right\">25</td>\n<td headers=\"IPV_binary\" class=\"gt_row gt_right\">0</td>\n<td headers=\"IPV_ordinal\" class=\"gt_row gt_center\">0</td>\n<td headers=\"m1natwt\" class=\"gt_row gt_right\">121.76894</td>\n<td headers=\"m1natwt_rep1\" class=\"gt_row gt_right\">129.03618</td>\n<td headers=\"m1natwt_rep2\" class=\"gt_row gt_right\">131.50407</td>\n<td headers=\"m1natwt_rep3\" class=\"gt_row gt_right\">124.49722</td>\n<td headers=\"m1natwt_rep4\" class=\"gt_row gt_right\">125.08351</td>\n<td headers=\"m1natwt_rep5\" class=\"gt_row gt_right\">115.39091</td>\n<td headers=\"m1natwt_rep6\" class=\"gt_row gt_right\">124.86470</td>\n<td headers=\"m1natwt_rep7\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep8\" class=\"gt_row gt_right\">131.66747</td>\n<td headers=\"m1natwt_rep9\" class=\"gt_row gt_right\">121.04597</td>\n<td headers=\"m1natwt_rep10\" class=\"gt_row gt_right\">126.42019</td>\n<td headers=\"m1natwt_rep11\" class=\"gt_row gt_right\">125.73327</td>\n<td headers=\"m1natwt_rep12\" class=\"gt_row gt_right\">120.78219</td>\n<td headers=\"m1natwt_rep13\" class=\"gt_row gt_right\">132.49487</td>\n<td headers=\"m1natwt_rep14\" class=\"gt_row gt_right\">114.30053</td>\n<td headers=\"m1natwt_rep15\" class=\"gt_row gt_right\">127.66466</td>\n<td headers=\"m1natwt_rep16\" class=\"gt_row gt_right\">124.08061</td>\n<td headers=\"m1natwt_rep17\" class=\"gt_row gt_right\">125.39723</td>\n<td headers=\"m1natwt_rep18\" class=\"gt_row gt_right\">130.57684</td>\n<td headers=\"m1natwt_rep19\" class=\"gt_row gt_right\">134.18793</td>\n<td headers=\"m1natwt_rep20\" class=\"gt_row gt_right\">122.83195</td>\n<td headers=\"m1natwt_rep21\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep22\" class=\"gt_row gt_right\">124.68690</td>\n<td headers=\"m1natwt_rep23\" class=\"gt_row gt_right\">119.24700</td>\n<td headers=\"m1natwt_rep24\" class=\"gt_row gt_right\">128.60410</td>\n<td headers=\"m1natwt_rep25\" class=\"gt_row gt_right\">128.66008</td>\n<td headers=\"m1natwt_rep26\" class=\"gt_row gt_right\">124.02149</td>\n<td headers=\"m1natwt_rep27\" class=\"gt_row gt_right\">126.49405</td>\n<td headers=\"m1natwt_rep28\" class=\"gt_row gt_right\">123.43700</td>\n<td headers=\"m1natwt_rep29\" class=\"gt_row gt_right\">141.58299</td>\n<td headers=\"m1natwt_rep30\" class=\"gt_row gt_right\">135.33669</td>\n<td headers=\"m1natwt_rep31\" class=\"gt_row gt_right\">126.14429</td>\n<td headers=\"m1natwt_rep32\" class=\"gt_row gt_right\">131.47270</td>\n<td headers=\"m1natwt_rep33\" class=\"gt_row gt_right\">125.73920</td></tr>\n    <tr><td headers=\"race\" class=\"gt_row gt_center\">White</td>\n<td headers=\"informal_support\" class=\"gt_row gt_right\">3</td>\n<td headers=\"IPV\" class=\"gt_row gt_right\">11</td>\n<td headers=\"informal_support_prop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_max\" class=\"gt_row gt_right\">3</td>\n<td headers=\"informal_support_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_ordinal\" class=\"gt_row gt_center\">3</td>\n<td headers=\"IPV_prop\" class=\"gt_row gt_right\">0.45833333</td>\n<td headers=\"IPV_max\" class=\"gt_row gt_right\">25</td>\n<td headers=\"IPV_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"IPV_ordinal\" class=\"gt_row gt_center\">11</td>\n<td headers=\"m1natwt\" class=\"gt_row gt_right\">85.96230</td>\n<td headers=\"m1natwt_rep1\" class=\"gt_row gt_right\">87.22457</td>\n<td headers=\"m1natwt_rep2\" class=\"gt_row gt_right\">83.79171</td>\n<td headers=\"m1natwt_rep3\" class=\"gt_row gt_right\">91.27752</td>\n<td headers=\"m1natwt_rep4\" class=\"gt_row gt_right\">80.11185</td>\n<td headers=\"m1natwt_rep5\" class=\"gt_row gt_right\">88.11595</td>\n<td headers=\"m1natwt_rep6\" class=\"gt_row gt_right\">88.67043</td>\n<td headers=\"m1natwt_rep7\" class=\"gt_row gt_right\">90.75494</td>\n<td headers=\"m1natwt_rep8\" class=\"gt_row gt_right\">91.45559</td>\n<td headers=\"m1natwt_rep9\" class=\"gt_row gt_right\">85.68980</td>\n<td headers=\"m1natwt_rep10\" class=\"gt_row gt_right\">86.45096</td>\n<td headers=\"m1natwt_rep11\" class=\"gt_row gt_right\">92.47426</td>\n<td headers=\"m1natwt_rep12\" class=\"gt_row gt_right\">81.41688</td>\n<td headers=\"m1natwt_rep13\" class=\"gt_row gt_right\">99.84825</td>\n<td headers=\"m1natwt_rep14\" class=\"gt_row gt_right\">79.96129</td>\n<td headers=\"m1natwt_rep15\" class=\"gt_row gt_right\">85.80882</td>\n<td headers=\"m1natwt_rep16\" class=\"gt_row gt_right\">87.77487</td>\n<td headers=\"m1natwt_rep17\" class=\"gt_row gt_right\">89.85811</td>\n<td headers=\"m1natwt_rep18\" class=\"gt_row gt_right\">84.30115</td>\n<td headers=\"m1natwt_rep19\" class=\"gt_row gt_right\">95.09169</td>\n<td headers=\"m1natwt_rep20\" class=\"gt_row gt_right\">89.03872</td>\n<td headers=\"m1natwt_rep21\" class=\"gt_row gt_right\">90.58102</td>\n<td headers=\"m1natwt_rep22\" class=\"gt_row gt_right\">90.92682</td>\n<td headers=\"m1natwt_rep23\" class=\"gt_row gt_right\">102.89832</td>\n<td headers=\"m1natwt_rep24\" class=\"gt_row gt_right\">93.30130</td>\n<td headers=\"m1natwt_rep25\" class=\"gt_row gt_right\">94.10433</td>\n<td headers=\"m1natwt_rep26\" class=\"gt_row gt_right\">86.57666</td>\n<td headers=\"m1natwt_rep27\" class=\"gt_row gt_right\">88.45363</td>\n<td headers=\"m1natwt_rep28\" class=\"gt_row gt_right\">82.06447</td>\n<td headers=\"m1natwt_rep29\" class=\"gt_row gt_right\">89.72732</td>\n<td headers=\"m1natwt_rep30\" class=\"gt_row gt_right\">97.44034</td>\n<td headers=\"m1natwt_rep31\" class=\"gt_row gt_right\">91.89236</td>\n<td headers=\"m1natwt_rep32\" class=\"gt_row gt_right\">94.17548</td>\n<td headers=\"m1natwt_rep33\" class=\"gt_row gt_right\">0.00000</td></tr>\n    <tr><td headers=\"race\" class=\"gt_row gt_center\">Black</td>\n<td headers=\"informal_support\" class=\"gt_row gt_right\">3</td>\n<td headers=\"IPV\" class=\"gt_row gt_right\">2</td>\n<td headers=\"informal_support_prop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_max\" class=\"gt_row gt_right\">3</td>\n<td headers=\"informal_support_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"informal_support_ordinal\" class=\"gt_row gt_center\">3</td>\n<td headers=\"IPV_prop\" class=\"gt_row gt_right\">0.08333333</td>\n<td headers=\"IPV_max\" class=\"gt_row gt_right\">25</td>\n<td headers=\"IPV_binary\" class=\"gt_row gt_right\">1</td>\n<td headers=\"IPV_ordinal\" class=\"gt_row gt_center\">2</td>\n<td headers=\"m1natwt\" class=\"gt_row gt_right\">98.04827</td>\n<td headers=\"m1natwt_rep1\" class=\"gt_row gt_right\">101.53748</td>\n<td headers=\"m1natwt_rep2\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep3\" class=\"gt_row gt_right\">99.79310</td>\n<td headers=\"m1natwt_rep4\" class=\"gt_row gt_right\">97.24787</td>\n<td headers=\"m1natwt_rep5\" class=\"gt_row gt_right\">102.89133</td>\n<td headers=\"m1natwt_rep6\" class=\"gt_row gt_right\">105.71425</td>\n<td headers=\"m1natwt_rep7\" class=\"gt_row gt_right\">105.91802</td>\n<td headers=\"m1natwt_rep8\" class=\"gt_row gt_right\">102.19711</td>\n<td headers=\"m1natwt_rep9\" class=\"gt_row gt_right\">100.52937</td>\n<td headers=\"m1natwt_rep10\" class=\"gt_row gt_right\">103.41740</td>\n<td headers=\"m1natwt_rep11\" class=\"gt_row gt_right\">95.16078</td>\n<td headers=\"m1natwt_rep12\" class=\"gt_row gt_right\">97.53283</td>\n<td headers=\"m1natwt_rep13\" class=\"gt_row gt_right\">98.28993</td>\n<td headers=\"m1natwt_rep14\" class=\"gt_row gt_right\">103.28411</td>\n<td headers=\"m1natwt_rep15\" class=\"gt_row gt_right\">105.16373</td>\n<td headers=\"m1natwt_rep16\" class=\"gt_row gt_right\">102.85249</td>\n<td headers=\"m1natwt_rep17\" class=\"gt_row gt_right\">97.12798</td>\n<td headers=\"m1natwt_rep18\" class=\"gt_row gt_right\">107.91775</td>\n<td headers=\"m1natwt_rep19\" class=\"gt_row gt_right\">102.52666</td>\n<td headers=\"m1natwt_rep20\" class=\"gt_row gt_right\">107.20479</td>\n<td headers=\"m1natwt_rep21\" class=\"gt_row gt_right\">100.78193</td>\n<td headers=\"m1natwt_rep22\" class=\"gt_row gt_right\">95.96693</td>\n<td headers=\"m1natwt_rep23\" class=\"gt_row gt_right\">97.10217</td>\n<td headers=\"m1natwt_rep24\" class=\"gt_row gt_right\">101.69630</td>\n<td headers=\"m1natwt_rep25\" class=\"gt_row gt_right\">99.66428</td>\n<td headers=\"m1natwt_rep26\" class=\"gt_row gt_right\">101.72647</td>\n<td headers=\"m1natwt_rep27\" class=\"gt_row gt_right\">96.58415</td>\n<td headers=\"m1natwt_rep28\" class=\"gt_row gt_right\">95.98499</td>\n<td headers=\"m1natwt_rep29\" class=\"gt_row gt_right\">100.43622</td>\n<td headers=\"m1natwt_rep30\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"m1natwt_rep31\" class=\"gt_row gt_right\">105.47424</td>\n<td headers=\"m1natwt_rep32\" class=\"gt_row gt_right\">96.22710</td>\n<td headers=\"m1natwt_rep33\" class=\"gt_row gt_right\">95.11009</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nWe'll need to run two models --- the first predicting the mediator, the second predicting the outcome --- and feed these models into `mediation::mediate()`.\n\n## Issue 1: Correctly applying the Fragile Families weights\n\nWe fit the models using `survey::svyglm` in order to be able to take the weights into account. First, we need to tell `survey` that our data is weighted, which we do with the help of the `srvyr` package for tidyverse-like convenience. Our first attempt looked like this:\n\n``` r\ndat_weights <- dat |> \n  srvyr::as_survey_rep(\n    repweights = dplyr::contains(\"_rep\"),\n    weights = m1natwt,\n    combined_weights = TRUE\n  )\n```\n\nHowever, coming across this [CrossValidated question](https://stats.stackexchange.com/questions/409463/duplicating-stata-survey-design-using-svrepdesign-from-survey-package-in-r) and confirming with the Fragile Families guide to using the weights showed us that the code above fails to tell `survey` that we want to use jackknife variance estimation. From the [guide (PDF)](https://fragilefamilies.princeton.edu/sites/fragilefamilies/files/using_the_fragile_families_weights_waves_1_6.pdf), p. 2:\n\n> As described in the weights construction memo, the replicate weights require using jackknife estimation of standard errors.\n\nWoops.\n\nSo, to properly apply the weights, we run this code block instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_weights <- dat |> \n  srvyr::as_survey_rep(\n    repweights = dplyr::contains(\"_rep\"),\n    weights = m1natwt,\n    combined_weights = TRUE,\n    type = \"JKn\",\n    scales = 1,\n    rscales = 1,\n    mse = TRUE\n)\n```\n:::\n\n\n# Running the weighted models and mediation\n\nWith the weighted dataframe in hand, we can use `survey::svyglm` to fit our GLMs predicting `informal_support` and `IPV`.\n\nOur informal support variable is the sum of three items for which each mother could get a 1 or a 0 (indicating that she did or did not have access to that form of support). As such, it seems sensible to model it as a binomial outcome --- each mother has a certain number of \"successes\" out of three possible trials.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_1 <- survey::svyglm(\n  formula = informal_support_prop ~ race,\n  weights = informal_support_max,\n  design = dat_weights,\n  family = \"binomial\"\n)\n\nsummary(model_m_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nsurvey::svyglm(formula = informal_support_prop ~ race, weights = informal_support_max, \n    design = dat_weights, family = \"binomial\")\n\nSurvey design:\nCalled via srvyr\n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.6891     0.2778   13.28 2.48e-14 ***\nraceBlack    -1.7317     0.3972   -4.36 0.000133 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1299.299)\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n:::\n\n\nWe get the following warning many times:\n\n```         \nWarning: non-integer #successes in a binomial glm!\n```\n\nThis is `survey`'s way of asking us to specify the family as \"quasibinomial\" instead of \"binomial\", since our outcome is a proportion (weighted by the number of trials) and not binary. However, if we do that, `mediation` will not work with our models.\n\nOur IPV variable is the sum of twelve items for which each mother could get a score of 0, 1, or 2 (indicating how often she experienced a given form of violence from her partner). As such, it also seems sensible to model it as a binomial outcome --- each mother has a certain number of \"successes\" out of 24 possible \"trials\".[^3]\n\n[^3]: Another option, which we won't go into, would be to take the responses to the items themselves and use a multi-level ordinal model with item as the random grouping factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_1 <- survey::svyglm(\n  formula = IPV_prop ~ race + informal_support_prop,\n  weights = IPV_max,\n  design = dat_weights,\n  family = \"binomial\"\n)\n\nsummary(model_y_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nsurvey::svyglm(formula = IPV_prop ~ race + informal_support_prop, \n    weights = IPV_max, design = dat_weights, family = \"binomial\")\n\nSurvey design:\nCalled via srvyr\n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            -1.4968     0.2949  -5.075 1.89e-05 ***\nraceBlack               0.1207     0.1680   0.719  0.47794    \ninformal_support_prop  -0.7482     0.2678  -2.794  0.00899 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 291.4434)\n\nNumber of Fisher Scoring iterations: 5\n```\n:::\n:::\n\n\n(Here again we suppressed the warning that would have otherwise popped up.)\n\nFinally, our mediation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmed_1 <- mediation::mediate(\n  model.m = model_m_1,\n  model.y = model_y_1,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_prop\"\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nweights taken as sampling weights, not total number of trials\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in mediation::mediate(model.m = model_m_1, model.y = model_y_1, :\ntreatment and control values do not match factor levels; using White and Black\nas control and treatment, respectively\n```\n:::\n\n```{.r .cell-code}\nsummary(med_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value   \nACME (control)            0.00943      0.00134         0.02    0.01 **\nACME (treated)            0.01006      0.00152         0.02    0.01 **\nADE (control)             0.01063     -0.01989         0.04    0.50   \nADE (treated)             0.01126     -0.02190         0.04    0.50   \nTotal Effect              0.02069     -0.01077         0.05    0.19   \nProp. Mediated (control)  0.34142     -2.60458         4.57    0.20   \nProp. Mediated (treated)  0.38814     -2.33485         4.30    0.20   \nACME (average)            0.00975      0.00142         0.02    0.01 **\nADE (average)             0.01095     -0.02108         0.04    0.50   \nProp. Mediated (average)  0.36478     -2.46972         4.43    0.20   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 1000 \n```\n:::\n:::\n\n\nA small but statistically significant mediation effect! The warning about weights not being taken as total number of trials makes us nervous, but then again, we did give the models sampling weights, so maybe it's ok?\n\n## Issue 2: Mediation with \"multiple-trial binomial mediator\" runs for weighted but not for unweighted models?\n\nWe knew that we would eventually perform a sensitivity analysis where all models would be run without using the sampling weights. Running the previous steps with the `glm` command resulted in an issue:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_2 <- glm(\n  formula = informal_support_prop ~ race,\n  weights = informal_support_max,\n  data = dat,\n  family = \"binomial\"\n)\n\nmodel_y_2 <- glm(\n  formula = IPV_prop ~ race + informal_support_prop,\n  weights = IPV_max,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_2 <- mediation::mediate(\n  model.m = model_m_2,\n  model.y = model_y_2,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_prop\"\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in mediation::mediate(model.m = model_m_2, model.y = model_y_2, : weights on outcome and mediator models not identical\n```\n:::\n:::\n\n\nIt seems like `mediation::mediate` is taking the weights we pass to the GLM function (which correspond to total number of trials, not to sampling weights) as sampling weights, and complaining when it notices that these weights are not the same for the mediator and outcome models. Vasco perhaps clumsily posted this as an [issue on the mediation package Github](https://github.com/kosukeimai/mediation/issues/59), but at least for now there has been no answer. We can work around this by using an alternative way of specifying the same GLM model --- instead of using a proportion as an outcome and passing the number of trials through the `weights` argument, we can instead use a vector of \"successes\" and \"failures\" (which corresponds to the total number of trials minus the number of successes) as the outcome:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_2.1 <- glm(\n  formula = cbind(informal_support, informal_support_max - informal_support) ~ race,\n  data = dat,\n  family = \"binomial\"\n)\n\nmodel_y_2.1 <- glm(\n  formula = cbind(IPV, IPV_max - IPV) ~ race + informal_support_prop,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_2.1 <- mediation::mediate(\n  model.m = model_m_2.1,\n  model.y = model_y_2.1,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_prop\"\n)\n\nsummary(med_2.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value    \nACME (control)            0.00300      0.00158         0.00  <2e-16 ***\nACME (treated)            0.00330      0.00177         0.01  <2e-16 ***\nADE (control)             0.01295      0.00766         0.02  <2e-16 ***\nADE (treated)             0.01325      0.00781         0.02  <2e-16 ***\nTotal Effect              0.01625      0.01073         0.02  <2e-16 ***\nProp. Mediated (control)  0.18287      0.10220         0.32  <2e-16 ***\nProp. Mediated (treated)  0.20130      0.11420         0.34  <2e-16 ***\nACME (average)            0.00315      0.00167         0.00  <2e-16 ***\nADE (average)             0.01310      0.00775         0.02  <2e-16 ***\nProp. Mediated (average)  0.19208      0.10780         0.33  <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 1000 \n```\n:::\n:::\n\n\nSuccess! But at the cost of suspicion. The [documentation for the `mediate` function](https://www.rdocumentation.org/packages/mediation/versions/4.5.0/topics/mediate) warns us that (emphasis added):\n\n> As of version 4.0, the mediator model can be of either 'lm', 'glm' (or \\`bayesglm'), 'polr' (or \\`bayespolr'), 'gam', 'rq', \\`survreg', or \\`merMod' class, corresponding respectively to the linear regression models, generalized linear models, ordered response models, generalized additive models, quantile regression models, parametric duration models, or multilevel models.. For binary response models, the 'mediator' must be a numeric variable with values 0 or 1 as opposed to a factor. Quasi-likelihood-based inferences are not allowed for the mediator model because the functional form must be exactly specified for the estimation algorithm to work. **The 'binomial' family can only be used for binary response mediators and cannot be used for multiple-trial responses**. This is due to conflicts between how the latter type of models are implemented in [**`glm`**](https://www.rdocumentation.org/link/glm?package=mediation&version=4.5.0) and how 'mediate' is currently written.\n\nThus, until the package author clarifies whether this implementation results in correct estimates, we are cautious about trusting them.\n\n### Sanity check: comparing results with linear probability models\n\nAs a sanity check, to become a little more confident that `mediate` is working as intended even though it's not supposed to work well with a multiple-trial binomial mediator, we compare the results of our model that did run (`med_2.1`) with a mediation run on linear probability models (basically, using `lm()` instead of `glm()` even though the outcomes are proportions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_2.2 <- lm(\n  formula = informal_support_prop ~ race,\n  data = dat\n)\n\nmodel_y_2.2 <- lm(\n  formula = IPV_prop ~ race + informal_support_prop,\n  data = dat\n)\n\nmed_2.2 <- mediation::mediate(\n  model.m = model_m_2.2,\n  model.y = model_y_2.2,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_prop\"\n)\n\nsummary(med_2.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n               Estimate 95% CI Lower 95% CI Upper p-value    \nACME           0.003173     0.001456         0.01  <2e-16 ***\nADE            0.013384     0.000487         0.03   0.040 *  \nTotal Effect   0.016557     0.003600         0.03   0.008 ** \nProp. Mediated 0.190543     0.068757         0.82   0.008 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 1000 \n```\n:::\n:::\n\n\nThe results seem fairly similar, but this provides limited comfort.\n\n### Bonus finding: you can specify a mediator that is not technically the variable that your mediator model predicts\n\nNote that in the models used for `med_2.1` there is a potential discrepancy. The mediator model is formulated as `formula = cbind(informal_support, informal_support_max - informal_support) ~ race`, while the outcome model is formulated as `formula = cbind(IPV, IPV_max - IPV) ~ race + informal_support_prop`. So the outcome model is using `informal_support_prop` (our intended mediator) as a predictor of IPV, but the mediator model uses the variables `informal_support` and `informal_support_max` to internally generate the proportion of successes. In the call to `mediation::mediate` we can then specify `mediator = \"informal_support_prop\"`, and all seems to work as intended. What if we used `informal_support` as predictor in the outcome model instead? We can then specify `mediator = \"informal_support\"` and end up with something like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_2.3 <- glm(\n  formula = cbind(informal_support, informal_support_max - informal_support) ~ race,\n  data = dat,\n  family = \"binomial\"\n)\n\nmodel_y_2.3 <- glm(\n  formula = cbind(IPV, IPV_max - IPV) ~ race + informal_support,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_2.3 <- mediation::mediate(\n  model.m = model_m_2.3,\n  model.y = model_y_2.3,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support\"\n)\n\nsummary(med_2.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value    \nACME (control)           0.001136     0.000583         0.00  <2e-16 ***\nACME (treated)           0.001245     0.000652         0.00  <2e-16 ***\nADE (control)            0.017250     0.010016         0.02  <2e-16 ***\nADE (treated)            0.017358     0.010085         0.02  <2e-16 ***\nTotal Effect             0.018494     0.011187         0.03  <2e-16 ***\nProp. Mediated (control) 0.060274     0.029872         0.12  <2e-16 ***\nProp. Mediated (treated) 0.066315     0.032896         0.13  <2e-16 ***\nACME (average)           0.001190     0.000617         0.00  <2e-16 ***\nADE (average)            0.017304     0.010053         0.02  <2e-16 ***\nProp. Mediated (average) 0.063294     0.031348         0.12  <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 1000 \n```\n:::\n:::\n\n\nLooking at the last three rows (Average Causal Mediated Effect (average), Average Direct Effect (average), and Proportion Mediated (average)), the results seem different than the ones estimated in `med_2.1` (which used `informal_support_prop` as mediator) and `med.2.2` (which used linear proability models). But looking closer, you'll notice that the estimates related to the mediator, namely of the Average Causal Mediated Effect and the Proportion Mediated just seem to be divided by three!\n\nMy assumption about how that came to be: When we use `informal_support_prop`, which can only take values on the $(0, 1)$ interval, the ACME estimates correspond to the change in probability of IPV associated with going from 0 to 1 on the mediator and thus span the full range of the mediator. When we use `informal_support`, which takes values in the set $\\{0, 1, 2, 3\\}$, the estimates also correspond to the increase in probability of IPV associated with an increase of 1 on the mediator (e.g., from 0 to 1), but this is only $\\frac{1}{3}$ of the total possible way. Thus, applying this effect three times would be equivalent to moving from 0 to 3 on the mediator scale, the same as moving from 0 to 1 when the mediator is a proportion.[^4]\n\n[^4]: Of course, the effects mentioned here are not really the effects of moving from X to Y on the mediator, but the mediated effect that changing from Race = \"White\" to Race = \"Black\" has on the probability of IPV *through its effect on the mediator*.\n\n## Issue 3: Using a binary mediator and a binomial outcome --- works with cbind(successes, failures) but not with proportion as outcome and weights argument specified {#issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified}\n\nNext, we attempted to run everything with the same binomial outcome and a binary mediator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_3 <- glm(\n  formula = informal_support_binary ~ race,\n  data = dat,\n  family = \"binomial\"\n)\n\nmodel_y_3 <- glm(\n  formula = IPV_prop ~ race + informal_support_binary,\n  weights = IPV_max,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_3 <- mediation::mediate(\n  model.m = model_m_3,\n  model.y = model_y_3,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in mediation::mediate(model.m = model_m_3, model.y = model_y_3, : weights on outcome and mediator models not identical\n```\n:::\n:::\n\n\nOnce again we find that `mediate` complains about different weights on mediator and outcome models, even though, according to the documentation, it works with a binary mediator and a binomial outcome. We then try using the vector of successes and failures specification for the outcome model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_3.1 <- glm(\n  formula = cbind(IPV, IPV_max - IPV) ~ race + informal_support_binary,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_3.1 <- mediation::mediate(\n  model.m = model_m_3,\n  model.y = model_y_3.1,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nsummary(med_3.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value    \nACME (control)            0.00341      0.00145         0.01  <2e-16 ***\nACME (treated)            0.00375      0.00160         0.01  <2e-16 ***\nADE (control)             0.01225      0.00660         0.02  <2e-16 ***\nADE (treated)             0.01259      0.00682         0.02  <2e-16 ***\nTotal Effect              0.01600      0.00975         0.02  <2e-16 ***\nProp. Mediated (control)  0.21173      0.09966         0.37  <2e-16 ***\nProp. Mediated (treated)  0.23361      0.11244         0.39  <2e-16 ***\nACME (average)            0.00358      0.00152         0.01  <2e-16 ***\nADE (average)             0.01242      0.00670         0.02  <2e-16 ***\nProp. Mediated (average)  0.22267      0.10676         0.38  <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 1000 \n```\n:::\n:::\n\n\nThis approach runs, but we are still left wondering whether we can trust the estimates.\n\n## Issue 4: Ordinal mediator and binomial outcome don't work together\n\nBecause we would prefer not to binarize the social support variable in order to keep all the information that we can, we also explored using an ordinal mediator model. `mediate()` works with ordinal models fit with `MASS::polr`, so we attempted that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_4 <- MASS::polr(\n  formula = informal_support_ordinal ~ race,\n  data = dat,\n  Hess = TRUE\n)\n\nmodel_y_4 <- glm(\n  formula = cbind(IPV, IPV_max - IPV) ~ race + informal_support_ordinal,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_4 <- mediation::mediate(\n  model.m = model_m_4,\n  model.y = model_y_4,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\"\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in UseMethod(\"isSymmetric\"): no applicable method for 'isSymmetric' applied to an object of class \"c('double', 'numeric')\"\n```\n:::\n:::\n\n\nThe first issue arises, but it's easy to fix. Again, from the [documentation of the mediate function](https://rdrr.io/cran/mediation/man/mediate.html):\n\n> The quasi-Bayesian approximation (King et al. 2000) cannot be used if 'model.m' is of class 'rq' or 'gam', or if 'model.y' is of class 'gam', 'polr' or 'bayespolr'. In these cases, either an error message is returned or use of the nonparametric bootstrap is forced. Users should note that use of the nonparametric bootstrap often requires significant computing time, especially when 'sims' is set to a large value.\n\nWe can get around this by setting the argument `boot` to `TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmed_4 <- mediation::mediate(\n  model.m = model_m_4,\n  model.y = model_y_4,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\",\n  boot = TRUE\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cbind(IPV, IPV_max - IPV): object 'IPV' not found\n```\n:::\n:::\n\n\nNow we get a different problem. It seems the `boot` package is having trouble with the way we set up our outcome model --- hopefully using the other implementation will take care of that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_4.1 <- glm(\n  formula = IPV_prop ~ race + informal_support_ordinal,\n  weights = IPV_max,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_4 <- mediation::mediate(\n  model.m = model_m_4,\n  model.y = model_y_4.1,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\",\n  boot = TRUE\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in mediation::mediate(model.m = model_m_4, model.y = model_y_4.1, : weights on outcome and mediator models not identical\n```\n:::\n:::\n\n\nFinally, we reach a dead-end. It seems once again the `mediate` function is taking the prior weights we fed into our `glm` as sample weight and complaining that our ordinal model doesn't have the same sample weights. If we are willing to throw away some information, we can make it all work with a binary outcome, thusly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_4.2 <- glm(\n  formula = IPV_binary ~ race + informal_support_ordinal,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_4 <- mediation::mediate(\n  model.m = model_m_4,\n  model.y = model_y_4.2,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\",\n  boot = TRUE\n)\n\nsummary(med_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nNonparametric Bootstrap Confidence Intervals with the Percentile Method\n\n                          Estimate 95% CI Lower 95% CI Upper p-value\nACME (control)            0.004254    -0.000807         0.01    0.11\nACME (treated)            0.004133    -0.000843         0.01    0.12\nADE (control)             0.012614    -0.028090         0.06    0.54\nADE (treated)             0.012493    -0.028002         0.06    0.54\nTotal Effect              0.016747    -0.025355         0.06    0.43\nProp. Mediated (control)  0.254006    -1.540048         1.85    0.48\nProp. Mediated (treated)  0.246814    -1.589415         1.86    0.49\nACME (average)            0.004194    -0.000811         0.01    0.12\nADE (average)             0.012553    -0.028046         0.06    0.54\nProp. Mediated (average)  0.250410    -1.562177         1.86    0.49\n\nSample Size Used: 1955 \n\n\nSimulations: 1000 \n```\n:::\n:::\n\n\nThis runs, although the bootstrap adds significantly to computing time and we had to binarize IPV to achieve it.\n\n## Issue 5: mediate() is not compatible with svyolr() models\n\nWith this partial success, we checked to see if we could also run this latest mediation on the weighted data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_5 <- survey::svyolr(\n  formula = informal_support_ordinal ~ race,\n  design = dat_weights\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in optim(s0, fmin, gmin, method = \"BFGS\", ...): initial value in 'vmmin' is not finite\n```\n:::\n:::\n\n\nThis throws an error, which [this StackOverflow post](https://stackoverflow.com/questions/28916377/r-error-with-polr-initial-value-in-vmmin-is-not-finite?rq=2) can help us solve. We can help the function by providing plausible start values for the coefficients and the intercepts/thresholds. We have one coefficient and three thresholds (from 0 to 1, from 1 to 2, and from 2 to 3), and we know they should be relatively close to zero as well as that the thresholds should be in ascending order. With the syntax `start = c(coefficients, thresholds)` we can make it work:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_5 <- survey::svyolr(\n  formula = informal_support_ordinal ~ race,\n  design = dat_weights,\n  start = c(0, -1, 0, 1)\n)\n\nsummary(model_m_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\nsvyolr(formula = informal_support_ordinal ~ race, design = dat_weights, \n    start = c(0, -1, 0, 1))\n\nCoefficients:\n             Value Std. Error  t value\nraceBlack -1.62481  0.3874065 -4.19407\n\nIntercepts:\n    Value    Std. Error t value \n0|1  -4.5463   0.3580   -12.6979\n1|2  -3.7384   0.2741   -13.6376\n2|3  -3.0236   0.2458   -12.3027\n```\n:::\n:::\n\n\nOk, moving on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_5 <- survey::svyglm(\n  formula = IPV_binary ~ race + informal_support_ordinal,\n  design = dat_weights,\n  family = \"binomial\"\n)\n\nmed_5 <- mediation::mediate(\n  model.m = model_m_5,\n  model.y = model_y_5,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\",\n  boot = TRUE\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in mediation::mediate(model.m = model_m_5, model.y = model_y_5, : weights on outcome and mediator models not identical\n```\n:::\n:::\n\n\nNot this again 😭. We knew that the weights used for the `svyglm()` and `svyolr()` models were the same, so there must be something else happening in the background. Vasco did some investigating and again [turned to Stack Overflow](https://stackoverflow.com/questions/76900094/inconsistent-weights-with-lumleys-survey-package-svyglm-vs-svyolr-error-or-b). We can see what weights are stored in the model objects generated by `svyglm()` and `svyolr()` using the `model.frame()` function. In the following two code blocks we also use `dplyr::slice_head()` to display just the first line of results output by `model.frame().`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.frame(model_m_5) |> dplyr::slice_head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  informal_support_ordinal  race (weights)\n1                        3 Black  41.13614\n```\n:::\n\n```{.r .cell-code}\nmodel.frame(model_y_5) |> dplyr::slice_head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  IPV_binary  race informal_support_ordinal (weights)\n1          1 Black                        3 0.1142592\n```\n:::\n:::\n\n\nThe first weight for our ordinal model appears to be 41.13614, while the binomial model uses 0.1142592. We can extract all the weights for both models and compare them. Let's look at their ratio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweight_comparison <- tibble::tibble(\n  binomial_weights = model.frame(model_y_5)$`(weights)`,\n  ordinal_weights = model.frame(model_m_5)$`(weights)`,\n  weight_quotient = binomial_weights / ordinal_weights\n)\n\nweight_comparison |> dplyr::slice_head(n = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n  binomial_weights ordinal_weights weight_quotient\n             <dbl>           <dbl>           <dbl>\n1           0.114             41.1         0.00278\n2           0.0555            20.0         0.00278\n3           0.0340            12.2         0.00278\n4           0.338            122.          0.00278\n5           0.239             86.0         0.00278\n```\n:::\n:::\n\n\nWould you look at that! The ratio seems to be constant. We can check the entire `weight_quotient` column just to be extra sure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweight_comparison |> dplyr::count(weight_quotient)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  weight_quotient     n\n            <dbl> <int>\n1         0.00278   218\n2         0.00278  1733\n3         0.00278     4\n```\n:::\n:::\n\n\nThere seem to be three different values that all look the same --- perhaps this will make more sense once we learn more about floating point arithmetic, but for now we'll say the ratio between the weights is always the same. On Stack Overflow, Thomas Lumley, maintainer of the `survey` package, explains in a reply to my post:\n\n> Some functions in the survey package rescale the weights to have unit mean because the large weights (thousands or tens of thousands) in some national surveys can cause convergence problems.\n>\n> Since the results aren't affected at all, the `mediate` package could probably work around this fairly easily. However, there's a `rescale=FALSE` option to `svyglm` to not rescale the weights, provided for this sort of purpose.\n>\n> If you then have convergence problems in `svyglm` you could manually rescale the weights to have unit mean before doing any of the analyses.\n\nGood to know!\n\nLet's set `rescale = FALSE` in the `svyglm` model and try our luck:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_5.1 <- survey::svyglm(\n  formula = IPV_binary ~ race + informal_support_ordinal,\n  design = dat_weights,\n  family = \"binomial\",\n  rescale = FALSE\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in is.data.frame(pwts): object 'pwts' not found\n```\n:::\n:::\n\n\nThis is perplexing, but [someone else on Stack Overflow](https://stackoverflow.com/questions/66465401/error-with-svyglm-function-in-survey-package-in-r-all-variables-must-be-in-des) a couple of years ago encountered a similar problem, where object \".survey.prob.weights\" was not found when `rescale` was set to `FALSE`. After looking at the [source code](https://rdrr.io/rforge/survey/src/R/surveyrep.R) and the [accepted answer by user xilliam](https://stackoverflow.com/a/66474985/12296038) to the Stack Overflow post, we try to assign the prior weights contained in the survey design object to an object named `pwts` in the global environment, and that makes `svyglm()` happy again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwts <- dat_weights$pweights\n\nmodel_y_5.1 <- survey::svyglm(\n  formula = IPV_binary ~ race + informal_support_ordinal,\n  design = dat_weights,\n  family = \"binomial\",\n  rescale = FALSE\n)\n\n# remove pwts from the global environment\nrm(list = \"pwts\")\n```\n:::\n\n\nHowever, we can't be sure if this correctly solves the problem or introduces new errors. To ask the package maintainer (or anyone else who might know) more directly, Vasco posed this problem in a new Stack Overflow post. XXX LINK MISSING\n\nNow we try to run the mediation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmed_5 <- mediation::mediate(\n  model.m = model_m_5,\n  model.y = model_y_5.1,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\",\n  boot = TRUE\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in MASS::polr(formula, data = df, ..., Hess = TRUE, model = FALSE, : formal argument \"data\" matched by multiple actual arguments\n```\n:::\n:::\n\n\nSomehow it is not working again. What if the outcome model was ordinal as well, just for fun?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_y_5.2 <- survey::svyolr(\n  formula = IPV_ordinal ~ race + informal_support_ordinal,\n  design = dat_weights,\n  start = c(0, 0, 0, 0, seq(from = -1, to = 1, length.out = 24))\n)\n\nmed_5 <- mediation::mediate(\n  model.m = model_m_5,\n  model.y = model_y_5.2,\n  sims = n_sims,\n  treat = \"race\",\n  mediator = \"informal_support_ordinal\",\n  boot = TRUE\n)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in MASS::polr(formula, data = df, ..., Hess = TRUE, model = FALSE, : formal argument \"data\" matched by multiple actual arguments\n```\n:::\n:::\n\n\nOk, we give up here.\n\n## Issue 6: Options and choices to boot --- To robustSE or not to robustSE?\n\nFor now, we've ignored an optional setting to `mediate()`: the `robustSE` argument defaults to `FALSE`, and, according to [the documentation](https://www.rdocumentation.org/packages/mediation/versions/4.5.0/topics/mediate), \"If 'TRUE', heteroskedasticity-consistent standard errors will be used in quasi-Bayesian simulations. Ignored if 'boot' is 'TRUE' or neither 'model.m' nor 'model.y' has a method for **`vcovHC`** in the **`sandwich`** package.\" So we have three options:\n\n1.  `boot = TRUE` and, automatically, `robustSE = FALSE`\n2.  `boot = FALSE` and `robustSE = TRUE`, and\n3.  `boot = FALSE` and `robustSE = FALSE`.\n\nAnd we know that, when chosen, the heteroskedasticity-consistent standard errors will be calculated with the help of the `sandwich` package.\n\nAccording to the `mediation` package [vignettes](https://cran.r-project.org/web/packages/mediation/vignettes/mediation.pdf), the authors recommend setting `boot = TRUE`: \"In general, as long as computing power is not an issue, analysts should estimate confidence intervals via the bootstrap with more than 1000 resamples, which is the default number of simulations.\" So we could do that. Unfortunately, computing power *is* an issue, as we wanted to run a multiverse analysis that meant we would use the `mediate()` function a bunch of times. To figure out whether to set `robustSE` to `TRUE` or `FALSE`, it could be useful to see which option gives use results that are closer to the bootstrap option. Let's use a binary mediator and outcome, just so we are sure there aren't other issues at play.\n\nFirst, we compare unweighted models. To reduce simulation-dependent variability, we set `sims = 3000`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_6 <- glm(\n  formula = informal_support_binary ~ race,\n  data = dat,\n  family = \"binomial\"\n)\n\nmodel_y_6 <- glm(\n  formula = IPV_binary ~ race + informal_support_binary,\n  data = dat,\n  family = \"binomial\"\n)\n\nmed_6.1 <- mediation::mediate(\n  model.m = model_m_6,\n  model.y = model_y_6,\n  sims = 3000,\n  boot = TRUE,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nmed_6.2 <- mediation::mediate(\n  model.m = model_m_6,\n  model.y = model_y_6,\n  sims = 3000,\n  robustSE = TRUE,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nmed_6.3 <- mediation::mediate(\n  model.m = model_m_6,\n  model.y = model_y_6,\n  sims = 3000,\n  robustSE = FALSE,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nsummary(med_6.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nNonparametric Bootstrap Confidence Intervals with the Percentile Method\n\n                          Estimate 95% CI Lower 95% CI Upper p-value  \nACME (control)            4.26e-03    -3.86e-05         0.01   0.051 .\nACME (treated)            4.17e-03    -3.50e-05         0.01   0.051 .\nADE (control)             1.07e-02    -2.88e-02         0.05   0.645  \nADE (treated)             1.06e-02    -2.85e-02         0.05   0.645  \nTotal Effect              1.49e-02    -2.46e-02         0.06   0.515  \nProp. Mediated (control)  2.86e-01    -2.45e+00         2.54   0.541  \nProp. Mediated (treated)  2.80e-01    -2.47e+00         2.57   0.541  \nACME (average)            4.22e-03    -3.68e-05         0.01   0.051 .\nADE (average)             1.07e-02    -2.85e-02         0.05   0.645  \nProp. Mediated (average)  2.83e-01    -2.46e+00         2.56   0.541  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n\n```{.r .cell-code}\nsummary(med_6.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                          Estimate 95% CI Lower 95% CI Upper p-value  \nACME (control)            4.10e-03    -3.72e-05         0.01   0.051 .\nACME (treated)            4.02e-03    -3.59e-05         0.01   0.051 .\nADE (control)             1.04e-02    -3.07e-02         0.05   0.627  \nADE (treated)             1.03e-02    -3.04e-02         0.05   0.627  \nTotal Effect              1.44e-02    -2.68e-02         0.06   0.506  \nProp. Mediated (control)  1.26e-01    -2.43e+00         2.56   0.536  \nProp. Mediated (treated)  1.20e-01    -2.45e+00         2.57   0.536  \nACME (average)            4.06e-03    -3.65e-05         0.01   0.051 .\nADE (average)             1.03e-02    -3.05e-02         0.05   0.627  \nProp. Mediated (average)  1.23e-01    -2.44e+00         2.57   0.536  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n\n```{.r .cell-code}\nsummary(med_6.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                          Estimate 95% CI Lower 95% CI Upper p-value  \nACME (control)            0.004040    -0.000299         0.01   0.071 .\nACME (treated)            0.003967    -0.000293         0.01   0.071 .\nADE (control)             0.010080    -0.030357         0.05   0.643  \nADE (treated)             0.010006    -0.030131         0.05   0.643  \nTotal Effect              0.014046    -0.025226         0.05   0.512  \nProp. Mediated (control)  0.127462    -2.935704         2.62   0.549  \nProp. Mediated (treated)  0.120777    -2.984962         2.64   0.549  \nACME (average)            0.004003    -0.000299         0.01   0.071 .\nADE (average)             0.010043    -0.030260         0.05   0.643  \nProp. Mediated (average)  0.124119    -2.954850         2.63   0.549  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n:::\n\n\nWe can see that the results are very similar, and in fact running the mediations several times reveals that the difference seems to be due to simulation variability. Given this, Vasco would personally rather specify `robustSE = FALSE`, since it does not make sense to correct for heteroskedasticity in a logistic regression model which *cannot suffer from* heteroskedasticity in the first place.\n\nWhat about if we use weighted models?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_m_6.1 <- survey::svyglm(\n  formula = informal_support_binary ~ race,\n  design = dat_weights,\n  family = \"binomial\"\n)\n\nmodel_y_6.1 <- survey::svyglm(\n  formula = IPV_binary ~ race + informal_support_binary,\n  design = dat_weights,\n  family = \"binomial\"\n)\n\nmed_6.4 <- mediation::mediate(\n  model.m = model_m_6.1,\n  model.y = model_y_6.1,\n  sims = 3000,\n  boot = TRUE,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nmed_6.5 <- mediation::mediate(\n  model.m = model_m_6.1,\n  model.y = model_y_6.1,\n  sims = 3000,\n  robustSE = TRUE,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nmed_6.6 <- mediation::mediate(\n  model.m = model_m_6.1,\n  model.y = model_y_6.1,\n  sims = 3000,\n  robustSE = FALSE,\n  treat = \"race\",\n  mediator = \"informal_support_binary\"\n)\n\nsummary(med_6.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nNonparametric Bootstrap Confidence Intervals with the Percentile Method\n\n                         Estimate 95% CI Lower 95% CI Upper p-value    \nACME (control)            0.01714      0.01014         0.02  <2e-16 ***\nACME (treated)            0.01601      0.00947         0.02  <2e-16 ***\nADE (control)             0.02840      0.02823         0.03  <2e-16 ***\nADE (treated)             0.02728      0.02710         0.03  <2e-16 ***\nTotal Effect              0.04441      0.03780         0.05  <2e-16 ***\nProp. Mediated (control)  0.38582      0.26805         0.43  <2e-16 ***\nProp. Mediated (treated)  0.36046      0.25043         0.40  <2e-16 ***\nACME (average)            0.01657      0.00981         0.02  <2e-16 ***\nADE (average)             0.02784      0.02774         0.03  <2e-16 ***\nProp. Mediated (average)  0.37314      0.25924         0.42  <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n\n```{.r .cell-code}\nsummary(med_6.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value    \nACME (control)            0.01500      0.00983         0.02  <2e-16 ***\nACME (treated)            0.01401      0.00919         0.02  <2e-16 ***\nADE (control)             0.02837      0.01486         0.04  <2e-16 ***\nADE (treated)             0.02738      0.01436         0.04  <2e-16 ***\nTotal Effect              0.04238      0.02787         0.06  <2e-16 ***\nProp. Mediated (control)  0.35362      0.24308         0.52  <2e-16 ***\nProp. Mediated (treated)  0.32947      0.22232         0.50  <2e-16 ***\nACME (average)            0.01451      0.00952         0.02  <2e-16 ***\nADE (average)             0.02788      0.01462         0.04  <2e-16 ***\nProp. Mediated (average)  0.34154      0.23356         0.51  <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n\n```{.r .cell-code}\nsummary(med_6.6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value\nACME (control)            0.01437     -0.00657         0.04    0.17\nACME (treated)            0.01374     -0.00604         0.04    0.17\nADE (control)             0.02615     -0.09404         0.14    0.66\nADE (treated)             0.02551     -0.09102         0.14    0.66\nTotal Effect              0.03989     -0.07950         0.15    0.49\nProp. Mediated (control)  0.14616     -3.01393         3.19    0.59\nProp. Mediated (treated)  0.12193     -3.14578         3.36    0.59\nACME (average)            0.01406     -0.00629         0.04    0.17\nADE (average)             0.02583     -0.09256         0.14    0.66\nProp. Mediated (average)  0.13404     -3.09737         3.28    0.59\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n:::\n\n\nWhile the estimates are similar, the confidence intervals are *much* tighter when `boot` or `robustSE` are set to `TRUE`, and suddenly all estimates are significant! What gives?\n\nFirst, an [answer by Thomas Lumley](https://stackoverflow.com/a/75128332/12296038) (maintainer of the `survey` package) on Stack Overflow suggests that bootstrapping doesn't work well with these survey-weighted models, although his answer does not fully map to our situation. In [another answer](https://stackoverflow.com/a/56317510/12296038), this time about applying robust standard errors with the `sandwich` package[^5], Lumley is clearer: \"For `svyglm` models, `vcov()` already produces the appropriate sandwich estimator, and I don't think the \"sandwich\" package knows enough about the internals of the object to get it right.\" A few years prior, Achim Zeileis, maintainer of the `sandwich` package, had given [a different perspective](https://stackoverflow.com/a/28840854/12296038) which also boils down to **do not use `sandwich`** **on models fit with `survey`**.\n\n[^5]: Which Lumley apparently has also worked on!\n\nThere you have it, `boot = FALSE` and `robustSE = FALSE` is the way to go.\n\n### Bonus: this goes for using `marginaleffects` as well\n\nOften we are not interested in mediation, but rather would like a clean and interpretable way to report results from our GLMs. One could not be faulted for preferring to do this on the predicted probabilities scale rather than dealing with odds-ratios and other headaches. For this, the `marginaleffects` package can be of enormous help.\n\nFor example, we can examine the predicted probability of experiencing IPV for Black and White women:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarginaleffects::avg_predictions(\n  model = model_y_6.1,\n  variables = \"race\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  race Estimate Std. Error    z Pr(>|z|) 2.5 % 97.5 %\n White    0.699     0.0399 17.5   <0.001 0.620  0.777\n Black    0.726     0.0444 16.4   <0.001 0.639  0.813\n\nColumns: race, estimate, std.error, statistic, p.value, conf.low, conf.high \n```\n:::\n:::\n\n\nAnd then compare the probabilities themselves, for which we again have the option of \"correcting\" the standard errors via the `vcov` argument. Look at the difference in the confidence intervals and p-values spit out when we don't or do specify `vcov = \"HC\"`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarginaleffects::avg_comparisons(\n  model = model_y_6.1,\n  variables = \"race\"\n) |> gt::gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ylgbzxlykx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ylgbzxlykx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ylgbzxlykx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ylgbzxlykx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ylgbzxlykx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ylgbzxlykx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ylgbzxlykx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ylgbzxlykx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ylgbzxlykx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ylgbzxlykx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ylgbzxlykx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ylgbzxlykx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ylgbzxlykx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ylgbzxlykx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ylgbzxlykx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ylgbzxlykx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ylgbzxlykx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ylgbzxlykx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ylgbzxlykx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ylgbzxlykx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ylgbzxlykx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ylgbzxlykx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ylgbzxlykx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ylgbzxlykx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ylgbzxlykx .gt_left {\n  text-align: left;\n}\n\n#ylgbzxlykx .gt_center {\n  text-align: center;\n}\n\n#ylgbzxlykx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ylgbzxlykx .gt_font_normal {\n  font-weight: normal;\n}\n\n#ylgbzxlykx .gt_font_bold {\n  font-weight: bold;\n}\n\n#ylgbzxlykx .gt_font_italic {\n  font-style: italic;\n}\n\n#ylgbzxlykx .gt_super {\n  font-size: 65%;\n}\n\n#ylgbzxlykx .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ylgbzxlykx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ylgbzxlykx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ylgbzxlykx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ylgbzxlykx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ylgbzxlykx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ylgbzxlykx .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"contrast\">contrast</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">race</td>\n<td headers=\"contrast\" class=\"gt_row gt_left\">Black - White</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.02783414</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.06101841</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.4561596</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.6482752</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.09175976</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.147428</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\nmarginaleffects::avg_comparisons(\n  model = model_y_6.1,\n  variables = \"race\",\n  vcov = \"HC\"\n) |> gt::gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"rgeierqpdt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#rgeierqpdt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rgeierqpdt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rgeierqpdt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rgeierqpdt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rgeierqpdt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rgeierqpdt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rgeierqpdt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rgeierqpdt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rgeierqpdt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rgeierqpdt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rgeierqpdt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rgeierqpdt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rgeierqpdt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rgeierqpdt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgeierqpdt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rgeierqpdt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rgeierqpdt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgeierqpdt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rgeierqpdt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgeierqpdt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rgeierqpdt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgeierqpdt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rgeierqpdt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rgeierqpdt .gt_left {\n  text-align: left;\n}\n\n#rgeierqpdt .gt_center {\n  text-align: center;\n}\n\n#rgeierqpdt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rgeierqpdt .gt_font_normal {\n  font-weight: normal;\n}\n\n#rgeierqpdt .gt_font_bold {\n  font-weight: bold;\n}\n\n#rgeierqpdt .gt_font_italic {\n  font-style: italic;\n}\n\n#rgeierqpdt .gt_super {\n  font-size: 65%;\n}\n\n#rgeierqpdt .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#rgeierqpdt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rgeierqpdt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rgeierqpdt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rgeierqpdt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rgeierqpdt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rgeierqpdt .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"contrast\">contrast</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">race</td>\n<td headers=\"contrast\" class=\"gt_row gt_left\">Black - White</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.02783414</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.006864551</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.054765</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">5.018481e-05</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.01437986</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.04128841</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThe estimates are the same, but the standard error (wrongly) becomes minuscule if we apply the \"correction\" for heteroskedasticity without realizing that `sandwich` does not work properly on models fit with `survey`.\n\n## Issue 7: Boundaries of the confidence intervals are rounded differently\n\nDid you notice? Each time we use `summary()` on a `mediate()` object, the lower boundary of the 95% CI is reported with 5 decimal places, while the upper boundary is reported with 2 decimal places. This also bothered Stack Overflow user sateayam over 4 years ago, and luckily user Roland [answered with a fix](https://stackoverflow.com/a/53852254):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrace(mediation:::print.summary.mediate, \n      at = 11,\n      tracer = quote({\n        printCoefmat <- function(x, digits) {\n          p <- x[, 4]\n          x[, 1:3] <- sprintf(\"%.6f\", x[, 1:3])\n          x[, 4] <- sprintf(\"%.2f\", p)\n          print(x, quote = FALSE, right = TRUE)\n        } \n      }),\n      print = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"print.summary.mediate\"\n```\n:::\n\n```{.r .cell-code}\nmediation:::print.summary.mediate(summary(med_6.6))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value\nACME (control)           0.014373    -0.006565     0.041344    0.17\nACME (treated)           0.013742    -0.006045     0.040415    0.17\nADE (control)            0.026145    -0.094040     0.144596    0.66\nADE (treated)            0.025514    -0.091018     0.138792    0.66\nTotal Effect             0.039887    -0.079497     0.152341    0.49\nProp. Mediated (control) 0.146155    -3.013931     3.188480    0.59\nProp. Mediated (treated) 0.121932    -3.145777     3.362464    0.59\nACME (average)           0.014057    -0.006286     0.041002    0.17\nADE (average)            0.025830    -0.092561     0.141364    0.66\nProp. Mediated (average) 0.134043    -3.097373     3.275472    0.59\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n\n```{.r .cell-code}\nuntrace(mediation:::print.summary.mediate)\n```\n:::\n\n\nUnfortunately, this solution also changes the way p-values are presented. Look again at the results from `med_6.5` and compare with the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrace(mediation:::print.summary.mediate, \n      at = 11,\n      tracer = quote({\n        printCoefmat <- function(x, digits) {\n          p <- x[, 4]\n          x[, 1:3] <- sprintf(\"%.6f\", x[, 1:3])\n          x[, 4] <- sprintf(\"%.2f\", p)\n          print(x, quote = FALSE, right = TRUE)\n        } \n      }),\n      print = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"print.summary.mediate\"\n```\n:::\n\n```{.r .cell-code}\nmediation:::print.summary.mediate(summary(med_6.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCausal Mediation Analysis \n\nQuasi-Bayesian Confidence Intervals\n\n                         Estimate 95% CI Lower 95% CI Upper p-value\nACME (control)           0.015000     0.009828     0.020297    0.00\nACME (treated)           0.014014     0.009188     0.018891    0.00\nADE (control)            0.028369     0.014861     0.041631    0.00\nADE (treated)            0.027384     0.014359     0.040247    0.00\nTotal Effect             0.042383     0.027869     0.056726    0.00\nProp. Mediated (control) 0.353616     0.243076     0.517594    0.00\nProp. Mediated (treated) 0.329468     0.222324     0.495835    0.00\nACME (average)           0.014507     0.009520     0.019553    0.00\nADE (average)            0.027876     0.014622     0.040982    0.00\nProp. Mediated (average) 0.341542     0.233562     0.507357    0.00\n\nSample Size Used: 1955 \n\n\nSimulations: 3000 \n```\n:::\n\n```{.r .cell-code}\nuntrace(mediation:::print.summary.mediate)\n```\n:::\n\n\nThe interim solution is to print the summary twice, once with the original function for expected p-value behavior, and another time with the edited function for confidence-interval consistency. Someone more well-versed might want to take a shot at adapting the code so that the behavior is maintained for the p-values[^6] and fixed for the confidence intervals.\n\n[^6]: Perhaps taking into account user2554330's [insight in another answer](https://stackoverflow.com/a/64830084) about how p-values are stored and printed.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}