---
title: "My Natural Rhythm"
subtitle: "Making sense of a busy mind"
date: "2023-09-16"
categories: [poetry, english, neurodiversity, adhd]
format: html
---

*First published on Medium for Bouncin' and Behavin' Poems ([link to original post](https://medium.com/the-bouncin-and-behavin-poetry-society/my-natural-rhythm-1224486a7dac?sk=a7e4c43beae9543a69bcee2383de0ea9)).*

My natural rhythm is some sort of waltz but\
It ebbs and it flows and it spins to a halt\
— Hits\
A wall\
Hurts\
Its head\
Tends\
Its wounds and\
Finds itself again, anew\
With in-breath and out-breath\
And joy in the one-two-three\
Rolling and rolling in thought loops, emotions, sensations\
Chaotic pentameter’s what I would call it\
If I bothered to go back and count.

If it ever stayed still long enough

If the stresses didn’t slip\
If order were maintained\
But it’s not — it comes and (it) wanes

All I can hope for is to notice\
The beauty of chaos and flows\
The serendipity of rhymes without reason\
To savor the freedom of knowing\
I’ll never stick to any rhythm I may find along the ways

One-two-three\
One-two-three\
Let me be me.

## **Some background for the curious**

Post ADHD and Autism diagnosis, I’ve been on a journey to learn to accept and live with myself the way that I am. Recently, the idea of “finding my rhythm” has been quite important. I can’t stick to a routine, but *some* structure to my days is beneficial — can I reconcile the parts of me that need familiarity and predictability with those that love getting pulled in random directions without apparent logic?

So it happened that I was doing dishes in the middle of the day, thinking about what I should do next. Lie down? Work? What makes the most sense? What’s my natural rhythm? And suddenly I was stuck. “My natural rhythm” just kept repeating in my head, in a loop. As it repeated, I noticed *its* rhythm — like a waltzy 3/4 or 6/8 — and the thought emerged, *My-NA-tu-ral-RHY-thm-is-SOME-kind-of-WALTZ-but* … That seemed perfect. Some waltzy dactyls, but introduced with an anacrusis and ending awkwardly — that’s what I had to do next. I jumped on my bed and a poem was born.

And in a way, that’s my natural rhythm. To be earnestly thinking about what the correct next course of action for my day is, and then become completely sidetracked by a random idea that became my temporary number one priority.

Hopefully you enjoyed it, at least :)
