project:
  type: website
  output-dir: docs

website:
  title: "Vasco Brazão"
  navbar:
    left:
      - text: "Home"
        href: https://vbrazao.github.io/website/
      - text: "Blog"
        href: https://vbrazao.github.io/blog/
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vbrazao
      - icon: linkedin
        href: https://www.linkedin.com/in/vascobrazao/
      - text: "{{< iconify icon-park-solid butterfly height=25 width=25 >}}"
        href: https://bsky.app/profile/vascobrazao.bsky.social
  google-analytics: "G-2XK3PRN887"

format:
  html:
    theme: simplex
    css: styles.css

editor: visual

# define the citation style for all posts that have bibliography
# this style was downloaded feb 5 2024 from 
# https://github.com/citation-style-language/styles/blob/master/apa.csl
csl: apa.csl

