project:
  type: website
  output-dir: docs

website:
  title: "Vasco Brazão"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vbrazao
      - icon: twitter
        href: https://twitter.com/vascobrazao
      - icon: linkedin
        href: https://www.linkedin.com/in/vascobrazao/
  google-analytics: "G-2XK3PRN887"

format:
  html:
    theme: simplex
    css: styles.css

editor: visual

