project:
  type: website
  output-dir: docs

website:
  title: "Vasco Brazão"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vbrazao
      - icon: twitter
        href: https://twitter.com/vascobrazao
      - icon: mastodon
        href: https://tech.lgbt/@vascobrazao
      - icon: linkedin
        href: https://www.linkedin.com/in/vascobrazao/
      - text: "{{< iconify fluent-emoji-flat blue-square height=25 width=25 >}}"
        href: https://bsky.app/profile/vascobrazao.bsky.social
  google-analytics: "G-2XK3PRN887"

format:
  html:
    theme: litera
    css: styles.css

editor: visual

