project:
  type: website
  output-dir: docs

website:
  title: "Vasco Brazão"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vbrazao
      - icon: twitter
        href: https://twitter.com/vascobrazao
      - icon: mastodon
        href: https://tech.lgbt/@vascobrazao
      - icon: linkedin
        href: https://www.linkedin.com/in/vascobrazao/
      - text: "{{< iconify icon-park-solid butterfly height=25 width=25 >}}"
        href: https://bsky.app/profile/vascobrazao.bsky.social
  google-analytics: "G-2XK3PRN887"

format:
  html:
    theme: 
      - litera
      - deseo.scss
    css: styles.css
    toc: true

editor: visual

# define the citation style for all posts that have bibliography
# this style was downloaded feb 5 2024 from 
# https://github.com/citation-style-language/styles/blob/master/apa.csl
csl: apa.csl

