---
title: "Medium Friend Links"
subtitle: "Or: Read my Medium posts for free"
date: "2023-09-26"
---

It seems I've taken to writing on Medium again. Find my account here: [\@vascobrazao](https://medium.com/@vascobrazao)

The possibility of earning some money with my writing is alluring, so I will paywall most, if not all, of my posts. You can read them for free by using the following links, which Medium calls "friend links":

-   2023-09-28: [**Ideologia de Género \| Gender Ideology** (BOUNCIN' AND BEHAVIN' INTERNATIONAL POETRY \| PORTUGUESE)](https://medium.com/the-bouncin-and-behavin-poetry-society/ideologia-de-g%C3%A9nero-gender-ideology-4a3ab75f9697?sk=83305e0fbceba73d8a70f868e26e4228)

-   2023-09-27: [**Back from the dread \|** A poem](https://medium.com/scuzzbucket/back-from-the-dread-6c7d496132a0?sk=6d5889f259f8b19a67b17309322f6e5b)

-   2023-09-24: [**How to Get Rich Quick (with Quips)** \| Two poems, zero tips (POEMS \| FREEVERSE \| LIMERICK)](https://medium.com/the-bouncin-and-behavin-poetry-society/how-to-get-rich-quick-with-quips-d4dfc4c93e94?sk=a3ed6ccd3188ef3bda473a27f5b78833)

-   2023-09-19: [**The Worst is Wrong and Boring** \| An eye roll at tedious bigots (POETRY \| FREEVERSE)](https://medium.com/the-bouncin-and-behavin-poetry-society/the-worst-is-wrong-and-boring-e0e581ef69c3?sk=cd3f4438608bfd155280f92251f2e18c)

-   2023-09-16: [**My Natural Rhythm** \| Making sense of a busy mind (POETRY \| FREEVERSE)](https://medium.com/the-bouncin-and-behavin-poetry-society/my-natural-rhythm-1224486a7dac?sk=a7e4c43beae9543a69bcee2383de0ea9)

-   2023-06-08: [**Devaneios pós twitter e pré aula de ucraniano \|** ---um poema](https://medium.com/@vascobrazao/devaneios-p%C3%B3s-twitter-e-pr%C3%A9-aula-de-ucraniano-62a431d4bbcf?sk=3efc06607c2f042c10a6683c3aac5523)

-   2023-03-10: [**Anti-fat bias, not 'obesity', is a problem worth fighting** \| Here's what changed my mind](https://medium.com/@vascobrazao/anti-fat-bias-not-obesity-is-a-problem-worth-fighting-10edb355b63d?sk=133baf62555b9a4e6e9f30bad8154a79)

-   2023-02-10: [**I used to think tidying was moral** \| It's not. It's functional. Let KC Davis tell you what that means.](https://medium.com/@vascobrazao/i-used-to-think-tidying-was-moral-773299d102d8?sk=9697fdcf4c56eeb82e3961afb0f60753)
