<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vasco Brazão, Priya Devendran">
<meta name="dcterms.date" content="2023-01-01">

<title>Vasco Brazão - Adventures in mediation analysis with weighted GLMs (temporary title)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/iconify-1.0.0-beta.2/iconify-icon.min.js"></script>
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2XK3PRN887"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2XK3PRN887', { 'anonymize_ip': true});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Vasco Brazão</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vbrazao"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/vascobrazao"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://tech.lgbt/@vascobrazao"><i class="bi bi-mastodon" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/vascobrazao/"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app/profile/vascobrazao.bsky.social">
 <span class="menu-text"><iconify-icon inline="" icon="fluent-emoji-flat:blue-square" width="25" height="25"></iconify-icon></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Adventures in mediation analysis with weighted GLMs (temporary title)</h1>
            <p class="subtitle lead">subtitle TBD</p>
                                <div class="quarto-categories">
                <div class="quarto-category">statistics</div>
                <div class="quarto-category">mediation</div>
                <div class="quarto-category">survey</div>
                <div class="quarto-category">glm</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Vasco Brazão, Priya Devendran </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 1, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a>
  <ul class="collapse">
  <li><a href="#issue-1-correctly-applying-the-fragile-families-weights" id="toc-issue-1-correctly-applying-the-fragile-families-weights" class="nav-link" data-scroll-target="#issue-1-correctly-applying-the-fragile-families-weights">Issue 1: Correctly applying the Fragile Families weights</a></li>
  </ul></li>
  <li><a href="#running-the-weighted-models-and-mediation" id="toc-running-the-weighted-models-and-mediation" class="nav-link" data-scroll-target="#running-the-weighted-models-and-mediation">Running the weighted models and mediation</a>
  <ul class="collapse">
  <li><a href="#issue-2-mediation-with-multiple-trial-binomial-mediator-runs-for-weighted-but-not-for-unweighted-models" id="toc-issue-2-mediation-with-multiple-trial-binomial-mediator-runs-for-weighted-but-not-for-unweighted-models" class="nav-link" data-scroll-target="#issue-2-mediation-with-multiple-trial-binomial-mediator-runs-for-weighted-but-not-for-unweighted-models">Issue 2: Mediation with “multiple-trial binomial mediator” runs for weighted but not for unweighted models?</a>
  <ul class="collapse">
  <li><a href="#sanity-check-comparing-results-with-linear-probability-models" id="toc-sanity-check-comparing-results-with-linear-probability-models" class="nav-link" data-scroll-target="#sanity-check-comparing-results-with-linear-probability-models">Sanity check: comparing results with linear probability models</a></li>
  <li><a href="#bonus-finding-you-can-specify-a-mediator-that-is-not-technically-the-variable-that-your-mediator-model-predicts" id="toc-bonus-finding-you-can-specify-a-mediator-that-is-not-technically-the-variable-that-your-mediator-model-predicts" class="nav-link" data-scroll-target="#bonus-finding-you-can-specify-a-mediator-that-is-not-technically-the-variable-that-your-mediator-model-predicts">Bonus finding: you can specify a mediator that is not technically the variable that your mediator model predicts</a></li>
  </ul></li>
  <li><a href="#issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified" id="toc-issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified" class="nav-link" data-scroll-target="#issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified">Issue 3: Using a binary mediator and a binomial outcome — works with cbind(successes, failures) but not with proportion as outcome and weights argument specified</a></li>
  <li><a href="#issue-4-ordinal-mediator-and-binomial-outcome-dont-work-together." id="toc-issue-4-ordinal-mediator-and-binomial-outcome-dont-work-together." class="nav-link" data-scroll-target="#issue-4-ordinal-mediator-and-binomial-outcome-dont-work-together.">Issue 4: Ordinal mediator and binomial outcome don’t work together.</a></li>
  <li><a href="#issue-5-reconciling-svyglm-and-svyolr-models" id="toc-issue-5-reconciling-svyglm-and-svyolr-models" class="nav-link" data-scroll-target="#issue-5-reconciling-svyglm-and-svyolr-models">Issue 5: Reconciling svyglm() and svyolr() models</a></li>
  <li><a href="#issue-6-options-and-choices-to-boot-to-robustse-or-not-to-robustse" id="toc-issue-6-options-and-choices-to-boot-to-robustse-or-not-to-robustse" class="nav-link" data-scroll-target="#issue-6-options-and-choices-to-boot-to-robustse-or-not-to-robustse">Issue 6: Options and choices to boot — To robustSE or not to robustSE?</a></li>
  <li><a href="#issue-7-boundaries-of-the-confidence-intervals-are-rounded-differently" id="toc-issue-7-boundaries-of-the-confidence-intervals-are-rounded-differently" class="nav-link" data-scroll-target="#issue-7-boundaries-of-the-confidence-intervals-are-rounded-differently">Issue 7: Boundaries of the confidence intervals are rounded differently</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>This blogpost documents the challenges we faced when attempting to run a mediation analysis using the <code>mediation</code> package with a binomial mediator and outcome while incorporating sampling weights into the analysis with the help of the <code>survey</code> package.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the packages we will use</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mediation)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># directory for the post (to change once post goes live)</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>post_folder <span class="ot">&lt;-</span> <span class="st">"wip_mediation-weighted-glm"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># number of simulations for mediation analysis</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>As part of a research program seeking to better understand intimate partner violence (IPV) through an intersectional lens, we wanted to use the <a href="https://ffcws.princeton.edu/">Future of Families &amp; Child Wellbeing Study</a><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> dataset to run a mediation analysis. The data come from a survey with a complex design, and baseline and replicate weights are provided for each participant in the “national” sample. These weights should allow us to make estimates nationally representative. (TO DO! point to the document where people can learn more about the weights <a href="https://ffcws.princeton.edu/sites/g/files/toruqf4356/files/ff_const_wgts.pdf" class="uri">https://ffcws.princeton.edu/sites/g/files/toruqf4356/files/ff_const_wgts.pdf</a>) Our mediator and outcome variables could reasonably be construed as binomial outcomes, and this was our preferred approach to fitting the necessary models. However, we encountered several difficulties XXX</p>
<p>This post has the following structure: First, we introduce the data we’ll use for the demonstrations and exemplify how we would like to have run the models (TO DO: rephrase or simply change depending on final structure).</p>
<section id="background" class="level1">
<h1>Background</h1>
<p>For demonstrative purposes we created a synthetic dataset using the <code>synthpop</code> package. This dataset mirrors the characteristics of our data without it being possible to identify any real individuals from it.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get synthetic dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"posts"</span>, post_folder, <span class="st">"data_reduced_synth.RDS"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># create other variables we will need</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">informal_support_prop =</span> informal_support<span class="sc">/</span><span class="dv">3</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">informal_support_max =</span> <span class="dv">3</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">informal_support_binary =</span> <span class="fu">ifelse</span>(informal_support <span class="sc">==</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">informal_support_ordinal =</span> forcats<span class="sc">::</span><span class="fu">as_factor</span>(informal_support) <span class="sc">|&gt;</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>      forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(<span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">IPV_prop =</span> IPV<span class="sc">/</span><span class="dv">24</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">IPV_max =</span> <span class="dv">25</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">IPV_binary =</span> <span class="fu">ifelse</span>(IPV <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">IPV_ordinal =</span> forcats<span class="sc">::</span><span class="fu">as_factor</span>(IPV) <span class="sc">|&gt;</span> </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>      forcats<span class="sc">::</span><span class="fu">fct_expand</span>(<span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4"</span>, <span class="st">"5"</span>, <span class="st">"6"</span>, <span class="st">"7"</span>, <span class="st">"8"</span>, <span class="st">"9"</span>, <span class="st">"10"</span>, <span class="st">"11"</span>, <span class="st">"12"</span>, <span class="st">"13"</span>, <span class="st">"14"</span>, <span class="st">"15"</span>, <span class="st">"16"</span>, <span class="st">"17"</span>, <span class="st">"18"</span>, <span class="st">"19"</span>, <span class="st">"20"</span>, <span class="st">"21"</span>, <span class="st">"22"</span>, <span class="st">"23"</span>, <span class="st">"24"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>      forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(<span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4"</span>, <span class="st">"5"</span>, <span class="st">"6"</span>, <span class="st">"7"</span>, <span class="st">"8"</span>, <span class="st">"9"</span>, <span class="st">"10"</span>, <span class="st">"11"</span>, <span class="st">"12"</span>, <span class="st">"13"</span>, <span class="st">"14"</span>, <span class="st">"15"</span>, <span class="st">"16"</span>, <span class="st">"17"</span>, <span class="st">"18"</span>, <span class="st">"19"</span>, <span class="st">"20"</span>, <span class="st">"21"</span>, <span class="st">"22"</span>, <span class="st">"23"</span>, <span class="st">"24"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We have three variables that will be used for mediation, <code>race</code> (“White” or “Black”), <code>informal_support</code> (an integer from 0 to 3), and <code>IPV</code> (an integer from 0 to 24). We manually create <code>_prop</code> and <code>_max</code> variables for informal support and IPV, so that we can use the proportion as an outcome in our GLMs and use the <code>weights</code> argument to specify the number of trials. We also create <code>informal_support_binary</code>, which classifies women as having high access to informal support (takes the value 1) when they score 3 out of 3, and low access (takes the value 0) when they score less than 3, as well as <code>IPV_binary</code>, which classifies women as having experienced some form of IPV (takes the value 1) if they score more than 0 and as not having experienced IPV (takes the value 0) if they score exactly 0. These binarized variables will become useful later on. Finally, we create the ordered factor <code>informal_support_ordinal</code>, to be used in ordinal models later on.</p>
<p>Each person also has a baseline weight, <code>m1natwt</code>, and 33 replicate weights, <code>m1natwt_rep1</code> and so on. Behold:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat) <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  gt<span class="sc">::</span><span class="fu">gt</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div id="ueqsijoxgi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#ueqsijoxgi) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#ueqsijoxgi) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#ueqsijoxgi) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#ueqsijoxgi) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#ueqsijoxgi) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#ueqsijoxgi) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#ueqsijoxgi) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#ueqsijoxgi) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#ueqsijoxgi) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#ueqsijoxgi) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#ueqsijoxgi) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#ueqsijoxgi) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#ueqsijoxgi) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#ueqsijoxgi) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ueqsijoxgi) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#ueqsijoxgi) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#ueqsijoxgi) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ueqsijoxgi) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#ueqsijoxgi) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ueqsijoxgi) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#ueqsijoxgi) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ueqsijoxgi) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#ueqsijoxgi) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#ueqsijoxgi) .gt_left {
  text-align: left;
}

:where(#ueqsijoxgi) .gt_center {
  text-align: center;
}

:where(#ueqsijoxgi) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#ueqsijoxgi) .gt_font_normal {
  font-weight: normal;
}

:where(#ueqsijoxgi) .gt_font_bold {
  font-weight: bold;
}

:where(#ueqsijoxgi) .gt_font_italic {
  font-style: italic;
}

:where(#ueqsijoxgi) .gt_super {
  font-size: 65%;
}

:where(#ueqsijoxgi) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#ueqsijoxgi) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#ueqsijoxgi) .gt_indent_1 {
  text-indent: 5px;
}

:where(#ueqsijoxgi) .gt_indent_2 {
  text-indent: 10px;
}

:where(#ueqsijoxgi) .gt_indent_3 {
  text-indent: 15px;
}

:where(#ueqsijoxgi) .gt_indent_4 {
  text-indent: 20px;
}

:where(#ueqsijoxgi) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="race">race</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="informal_support">informal_support</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="IPV">IPV</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt">m1natwt</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep1">m1natwt_rep1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep2">m1natwt_rep2</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep3">m1natwt_rep3</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep4">m1natwt_rep4</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep5">m1natwt_rep5</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep6">m1natwt_rep6</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep7">m1natwt_rep7</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep8">m1natwt_rep8</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep9">m1natwt_rep9</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep10">m1natwt_rep10</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep11">m1natwt_rep11</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep12">m1natwt_rep12</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep13">m1natwt_rep13</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep14">m1natwt_rep14</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep15">m1natwt_rep15</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep16">m1natwt_rep16</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep17">m1natwt_rep17</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep18">m1natwt_rep18</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep19">m1natwt_rep19</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep20">m1natwt_rep20</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep21">m1natwt_rep21</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep22">m1natwt_rep22</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep23">m1natwt_rep23</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep24">m1natwt_rep24</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep25">m1natwt_rep25</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep26">m1natwt_rep26</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep27">m1natwt_rep27</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep28">m1natwt_rep28</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep29">m1natwt_rep29</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep30">m1natwt_rep30</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep31">m1natwt_rep31</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep32">m1natwt_rep32</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="m1natwt_rep33">m1natwt_rep33</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="informal_support_prop">informal_support_prop</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="informal_support_max">informal_support_max</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="informal_support_binary">informal_support_binary</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="informal_support_ordinal">informal_support_ordinal</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="IPV_prop">IPV_prop</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="IPV_max">IPV_max</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="IPV_binary">IPV_binary</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="IPV_ordinal">IPV_ordinal</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="race" class="gt_row gt_center">Black</td>
<td headers="informal_support" class="gt_row gt_right">3</td>
<td headers="IPV" class="gt_row gt_right">18</td>
<td headers="m1natwt" class="gt_row gt_right">41.13614</td>
<td headers="m1natwt_rep1" class="gt_row gt_right">37.85516</td>
<td headers="m1natwt_rep2" class="gt_row gt_right">41.24734</td>
<td headers="m1natwt_rep3" class="gt_row gt_right">42.44724</td>
<td headers="m1natwt_rep4" class="gt_row gt_right">44.39487</td>
<td headers="m1natwt_rep5" class="gt_row gt_right">43.73881</td>
<td headers="m1natwt_rep6" class="gt_row gt_right">44.45506</td>
<td headers="m1natwt_rep7" class="gt_row gt_right">40.57142</td>
<td headers="m1natwt_rep8" class="gt_row gt_right">40.78370</td>
<td headers="m1natwt_rep9" class="gt_row gt_right">41.43095</td>
<td headers="m1natwt_rep10" class="gt_row gt_right">34.34425</td>
<td headers="m1natwt_rep11" class="gt_row gt_right">44.46661</td>
<td headers="m1natwt_rep12" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep13" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep14" class="gt_row gt_right">37.94593</td>
<td headers="m1natwt_rep15" class="gt_row gt_right">41.50523</td>
<td headers="m1natwt_rep16" class="gt_row gt_right">43.69954</td>
<td headers="m1natwt_rep17" class="gt_row gt_right">41.31135</td>
<td headers="m1natwt_rep18" class="gt_row gt_right">39.22795</td>
<td headers="m1natwt_rep19" class="gt_row gt_right">42.50257</td>
<td headers="m1natwt_rep20" class="gt_row gt_right">42.02170</td>
<td headers="m1natwt_rep21" class="gt_row gt_right">46.58911</td>
<td headers="m1natwt_rep22" class="gt_row gt_right">41.82341</td>
<td headers="m1natwt_rep23" class="gt_row gt_right">45.53830</td>
<td headers="m1natwt_rep24" class="gt_row gt_right">42.27204</td>
<td headers="m1natwt_rep25" class="gt_row gt_right">42.28968</td>
<td headers="m1natwt_rep26" class="gt_row gt_right">43.25393</td>
<td headers="m1natwt_rep27" class="gt_row gt_right">40.67841</td>
<td headers="m1natwt_rep28" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep29" class="gt_row gt_right">42.64928</td>
<td headers="m1natwt_rep30" class="gt_row gt_right">42.28931</td>
<td headers="m1natwt_rep31" class="gt_row gt_right">42.82657</td>
<td headers="m1natwt_rep32" class="gt_row gt_right">43.13633</td>
<td headers="m1natwt_rep33" class="gt_row gt_right">44.10038</td>
<td headers="informal_support_prop" class="gt_row gt_right">1</td>
<td headers="informal_support_max" class="gt_row gt_right">3</td>
<td headers="informal_support_binary" class="gt_row gt_right">1</td>
<td headers="informal_support_ordinal" class="gt_row gt_center">3</td>
<td headers="IPV_prop" class="gt_row gt_right">0.75000000</td>
<td headers="IPV_max" class="gt_row gt_right">25</td>
<td headers="IPV_binary" class="gt_row gt_right">1</td>
<td headers="IPV_ordinal" class="gt_row gt_center">18</td></tr>
    <tr><td headers="race" class="gt_row gt_center">Black</td>
<td headers="informal_support" class="gt_row gt_right">3</td>
<td headers="IPV" class="gt_row gt_right">4</td>
<td headers="m1natwt" class="gt_row gt_right">19.97570</td>
<td headers="m1natwt_rep1" class="gt_row gt_right">22.96839</td>
<td headers="m1natwt_rep2" class="gt_row gt_right">20.49259</td>
<td headers="m1natwt_rep3" class="gt_row gt_right">20.21818</td>
<td headers="m1natwt_rep4" class="gt_row gt_right">21.76786</td>
<td headers="m1natwt_rep5" class="gt_row gt_right">20.79500</td>
<td headers="m1natwt_rep6" class="gt_row gt_right">20.41886</td>
<td headers="m1natwt_rep7" class="gt_row gt_right">21.54646</td>
<td headers="m1natwt_rep8" class="gt_row gt_right">19.36423</td>
<td headers="m1natwt_rep9" class="gt_row gt_right">19.80069</td>
<td headers="m1natwt_rep10" class="gt_row gt_right">19.47093</td>
<td headers="m1natwt_rep11" class="gt_row gt_right">19.58197</td>
<td headers="m1natwt_rep12" class="gt_row gt_right">20.42065</td>
<td headers="m1natwt_rep13" class="gt_row gt_right">19.78305</td>
<td headers="m1natwt_rep14" class="gt_row gt_right">20.23575</td>
<td headers="m1natwt_rep15" class="gt_row gt_right">21.36903</td>
<td headers="m1natwt_rep16" class="gt_row gt_right">20.48008</td>
<td headers="m1natwt_rep17" class="gt_row gt_right">20.91415</td>
<td headers="m1natwt_rep18" class="gt_row gt_right">20.30889</td>
<td headers="m1natwt_rep19" class="gt_row gt_right">21.36875</td>
<td headers="m1natwt_rep20" class="gt_row gt_right">19.87386</td>
<td headers="m1natwt_rep21" class="gt_row gt_right">21.06265</td>
<td headers="m1natwt_rep22" class="gt_row gt_right">20.41880</td>
<td headers="m1natwt_rep23" class="gt_row gt_right">23.67257</td>
<td headers="m1natwt_rep24" class="gt_row gt_right">20.81135</td>
<td headers="m1natwt_rep25" class="gt_row gt_right">21.42606</td>
<td headers="m1natwt_rep26" class="gt_row gt_right">21.32215</td>
<td headers="m1natwt_rep27" class="gt_row gt_right">19.58435</td>
<td headers="m1natwt_rep28" class="gt_row gt_right">20.62730</td>
<td headers="m1natwt_rep29" class="gt_row gt_right">21.86095</td>
<td headers="m1natwt_rep30" class="gt_row gt_right">20.91533</td>
<td headers="m1natwt_rep31" class="gt_row gt_right">20.08396</td>
<td headers="m1natwt_rep32" class="gt_row gt_right">20.84812</td>
<td headers="m1natwt_rep33" class="gt_row gt_right">20.38860</td>
<td headers="informal_support_prop" class="gt_row gt_right">1</td>
<td headers="informal_support_max" class="gt_row gt_right">3</td>
<td headers="informal_support_binary" class="gt_row gt_right">1</td>
<td headers="informal_support_ordinal" class="gt_row gt_center">3</td>
<td headers="IPV_prop" class="gt_row gt_right">0.16666667</td>
<td headers="IPV_max" class="gt_row gt_right">25</td>
<td headers="IPV_binary" class="gt_row gt_right">1</td>
<td headers="IPV_ordinal" class="gt_row gt_center">4</td></tr>
    <tr><td headers="race" class="gt_row gt_center">Black</td>
<td headers="informal_support" class="gt_row gt_right">3</td>
<td headers="IPV" class="gt_row gt_right">0</td>
<td headers="m1natwt" class="gt_row gt_right">12.24003</td>
<td headers="m1natwt_rep1" class="gt_row gt_right">12.68406</td>
<td headers="m1natwt_rep2" class="gt_row gt_right">11.59396</td>
<td headers="m1natwt_rep3" class="gt_row gt_right">12.10748</td>
<td headers="m1natwt_rep4" class="gt_row gt_right">12.00069</td>
<td headers="m1natwt_rep5" class="gt_row gt_right">13.18730</td>
<td headers="m1natwt_rep6" class="gt_row gt_right">11.88648</td>
<td headers="m1natwt_rep7" class="gt_row gt_right">12.80008</td>
<td headers="m1natwt_rep8" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep9" class="gt_row gt_right">12.55978</td>
<td headers="m1natwt_rep10" class="gt_row gt_right">11.89597</td>
<td headers="m1natwt_rep11" class="gt_row gt_right">12.56892</td>
<td headers="m1natwt_rep12" class="gt_row gt_right">12.57526</td>
<td headers="m1natwt_rep13" class="gt_row gt_right">12.47836</td>
<td headers="m1natwt_rep14" class="gt_row gt_right">11.46254</td>
<td headers="m1natwt_rep15" class="gt_row gt_right">12.59188</td>
<td headers="m1natwt_rep16" class="gt_row gt_right">12.65551</td>
<td headers="m1natwt_rep17" class="gt_row gt_right">11.98436</td>
<td headers="m1natwt_rep18" class="gt_row gt_right">12.49196</td>
<td headers="m1natwt_rep19" class="gt_row gt_right">12.09257</td>
<td headers="m1natwt_rep20" class="gt_row gt_right">13.70510</td>
<td headers="m1natwt_rep21" class="gt_row gt_right">13.18920</td>
<td headers="m1natwt_rep22" class="gt_row gt_right">12.23701</td>
<td headers="m1natwt_rep23" class="gt_row gt_right">12.59980</td>
<td headers="m1natwt_rep24" class="gt_row gt_right">12.74326</td>
<td headers="m1natwt_rep25" class="gt_row gt_right">13.78494</td>
<td headers="m1natwt_rep26" class="gt_row gt_right">12.39277</td>
<td headers="m1natwt_rep27" class="gt_row gt_right">13.22096</td>
<td headers="m1natwt_rep28" class="gt_row gt_right">11.71815</td>
<td headers="m1natwt_rep29" class="gt_row gt_right">13.12761</td>
<td headers="m1natwt_rep30" class="gt_row gt_right">12.33747</td>
<td headers="m1natwt_rep31" class="gt_row gt_right">11.22335</td>
<td headers="m1natwt_rep32" class="gt_row gt_right">12.79405</td>
<td headers="m1natwt_rep33" class="gt_row gt_right">13.22079</td>
<td headers="informal_support_prop" class="gt_row gt_right">1</td>
<td headers="informal_support_max" class="gt_row gt_right">3</td>
<td headers="informal_support_binary" class="gt_row gt_right">1</td>
<td headers="informal_support_ordinal" class="gt_row gt_center">3</td>
<td headers="IPV_prop" class="gt_row gt_right">0.00000000</td>
<td headers="IPV_max" class="gt_row gt_right">25</td>
<td headers="IPV_binary" class="gt_row gt_right">0</td>
<td headers="IPV_ordinal" class="gt_row gt_center">0</td></tr>
    <tr><td headers="race" class="gt_row gt_center">Black</td>
<td headers="informal_support" class="gt_row gt_right">3</td>
<td headers="IPV" class="gt_row gt_right">0</td>
<td headers="m1natwt" class="gt_row gt_right">121.76894</td>
<td headers="m1natwt_rep1" class="gt_row gt_right">129.03618</td>
<td headers="m1natwt_rep2" class="gt_row gt_right">131.50407</td>
<td headers="m1natwt_rep3" class="gt_row gt_right">124.49722</td>
<td headers="m1natwt_rep4" class="gt_row gt_right">125.08351</td>
<td headers="m1natwt_rep5" class="gt_row gt_right">115.39091</td>
<td headers="m1natwt_rep6" class="gt_row gt_right">124.86470</td>
<td headers="m1natwt_rep7" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep8" class="gt_row gt_right">131.66747</td>
<td headers="m1natwt_rep9" class="gt_row gt_right">121.04597</td>
<td headers="m1natwt_rep10" class="gt_row gt_right">126.42019</td>
<td headers="m1natwt_rep11" class="gt_row gt_right">125.73327</td>
<td headers="m1natwt_rep12" class="gt_row gt_right">120.78219</td>
<td headers="m1natwt_rep13" class="gt_row gt_right">132.49487</td>
<td headers="m1natwt_rep14" class="gt_row gt_right">114.30053</td>
<td headers="m1natwt_rep15" class="gt_row gt_right">127.66466</td>
<td headers="m1natwt_rep16" class="gt_row gt_right">124.08061</td>
<td headers="m1natwt_rep17" class="gt_row gt_right">125.39723</td>
<td headers="m1natwt_rep18" class="gt_row gt_right">130.57684</td>
<td headers="m1natwt_rep19" class="gt_row gt_right">134.18793</td>
<td headers="m1natwt_rep20" class="gt_row gt_right">122.83195</td>
<td headers="m1natwt_rep21" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep22" class="gt_row gt_right">124.68690</td>
<td headers="m1natwt_rep23" class="gt_row gt_right">119.24700</td>
<td headers="m1natwt_rep24" class="gt_row gt_right">128.60410</td>
<td headers="m1natwt_rep25" class="gt_row gt_right">128.66008</td>
<td headers="m1natwt_rep26" class="gt_row gt_right">124.02149</td>
<td headers="m1natwt_rep27" class="gt_row gt_right">126.49405</td>
<td headers="m1natwt_rep28" class="gt_row gt_right">123.43700</td>
<td headers="m1natwt_rep29" class="gt_row gt_right">141.58299</td>
<td headers="m1natwt_rep30" class="gt_row gt_right">135.33669</td>
<td headers="m1natwt_rep31" class="gt_row gt_right">126.14429</td>
<td headers="m1natwt_rep32" class="gt_row gt_right">131.47270</td>
<td headers="m1natwt_rep33" class="gt_row gt_right">125.73920</td>
<td headers="informal_support_prop" class="gt_row gt_right">1</td>
<td headers="informal_support_max" class="gt_row gt_right">3</td>
<td headers="informal_support_binary" class="gt_row gt_right">1</td>
<td headers="informal_support_ordinal" class="gt_row gt_center">3</td>
<td headers="IPV_prop" class="gt_row gt_right">0.00000000</td>
<td headers="IPV_max" class="gt_row gt_right">25</td>
<td headers="IPV_binary" class="gt_row gt_right">0</td>
<td headers="IPV_ordinal" class="gt_row gt_center">0</td></tr>
    <tr><td headers="race" class="gt_row gt_center">White</td>
<td headers="informal_support" class="gt_row gt_right">3</td>
<td headers="IPV" class="gt_row gt_right">11</td>
<td headers="m1natwt" class="gt_row gt_right">85.96230</td>
<td headers="m1natwt_rep1" class="gt_row gt_right">87.22457</td>
<td headers="m1natwt_rep2" class="gt_row gt_right">83.79171</td>
<td headers="m1natwt_rep3" class="gt_row gt_right">91.27752</td>
<td headers="m1natwt_rep4" class="gt_row gt_right">80.11185</td>
<td headers="m1natwt_rep5" class="gt_row gt_right">88.11595</td>
<td headers="m1natwt_rep6" class="gt_row gt_right">88.67043</td>
<td headers="m1natwt_rep7" class="gt_row gt_right">90.75494</td>
<td headers="m1natwt_rep8" class="gt_row gt_right">91.45559</td>
<td headers="m1natwt_rep9" class="gt_row gt_right">85.68980</td>
<td headers="m1natwt_rep10" class="gt_row gt_right">86.45096</td>
<td headers="m1natwt_rep11" class="gt_row gt_right">92.47426</td>
<td headers="m1natwt_rep12" class="gt_row gt_right">81.41688</td>
<td headers="m1natwt_rep13" class="gt_row gt_right">99.84825</td>
<td headers="m1natwt_rep14" class="gt_row gt_right">79.96129</td>
<td headers="m1natwt_rep15" class="gt_row gt_right">85.80882</td>
<td headers="m1natwt_rep16" class="gt_row gt_right">87.77487</td>
<td headers="m1natwt_rep17" class="gt_row gt_right">89.85811</td>
<td headers="m1natwt_rep18" class="gt_row gt_right">84.30115</td>
<td headers="m1natwt_rep19" class="gt_row gt_right">95.09169</td>
<td headers="m1natwt_rep20" class="gt_row gt_right">89.03872</td>
<td headers="m1natwt_rep21" class="gt_row gt_right">90.58102</td>
<td headers="m1natwt_rep22" class="gt_row gt_right">90.92682</td>
<td headers="m1natwt_rep23" class="gt_row gt_right">102.89832</td>
<td headers="m1natwt_rep24" class="gt_row gt_right">93.30130</td>
<td headers="m1natwt_rep25" class="gt_row gt_right">94.10433</td>
<td headers="m1natwt_rep26" class="gt_row gt_right">86.57666</td>
<td headers="m1natwt_rep27" class="gt_row gt_right">88.45363</td>
<td headers="m1natwt_rep28" class="gt_row gt_right">82.06447</td>
<td headers="m1natwt_rep29" class="gt_row gt_right">89.72732</td>
<td headers="m1natwt_rep30" class="gt_row gt_right">97.44034</td>
<td headers="m1natwt_rep31" class="gt_row gt_right">91.89236</td>
<td headers="m1natwt_rep32" class="gt_row gt_right">94.17548</td>
<td headers="m1natwt_rep33" class="gt_row gt_right">0.00000</td>
<td headers="informal_support_prop" class="gt_row gt_right">1</td>
<td headers="informal_support_max" class="gt_row gt_right">3</td>
<td headers="informal_support_binary" class="gt_row gt_right">1</td>
<td headers="informal_support_ordinal" class="gt_row gt_center">3</td>
<td headers="IPV_prop" class="gt_row gt_right">0.45833333</td>
<td headers="IPV_max" class="gt_row gt_right">25</td>
<td headers="IPV_binary" class="gt_row gt_right">1</td>
<td headers="IPV_ordinal" class="gt_row gt_center">11</td></tr>
    <tr><td headers="race" class="gt_row gt_center">Black</td>
<td headers="informal_support" class="gt_row gt_right">3</td>
<td headers="IPV" class="gt_row gt_right">2</td>
<td headers="m1natwt" class="gt_row gt_right">98.04827</td>
<td headers="m1natwt_rep1" class="gt_row gt_right">101.53748</td>
<td headers="m1natwt_rep2" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep3" class="gt_row gt_right">99.79310</td>
<td headers="m1natwt_rep4" class="gt_row gt_right">97.24787</td>
<td headers="m1natwt_rep5" class="gt_row gt_right">102.89133</td>
<td headers="m1natwt_rep6" class="gt_row gt_right">105.71425</td>
<td headers="m1natwt_rep7" class="gt_row gt_right">105.91802</td>
<td headers="m1natwt_rep8" class="gt_row gt_right">102.19711</td>
<td headers="m1natwt_rep9" class="gt_row gt_right">100.52937</td>
<td headers="m1natwt_rep10" class="gt_row gt_right">103.41740</td>
<td headers="m1natwt_rep11" class="gt_row gt_right">95.16078</td>
<td headers="m1natwt_rep12" class="gt_row gt_right">97.53283</td>
<td headers="m1natwt_rep13" class="gt_row gt_right">98.28993</td>
<td headers="m1natwt_rep14" class="gt_row gt_right">103.28411</td>
<td headers="m1natwt_rep15" class="gt_row gt_right">105.16373</td>
<td headers="m1natwt_rep16" class="gt_row gt_right">102.85249</td>
<td headers="m1natwt_rep17" class="gt_row gt_right">97.12798</td>
<td headers="m1natwt_rep18" class="gt_row gt_right">107.91775</td>
<td headers="m1natwt_rep19" class="gt_row gt_right">102.52666</td>
<td headers="m1natwt_rep20" class="gt_row gt_right">107.20479</td>
<td headers="m1natwt_rep21" class="gt_row gt_right">100.78193</td>
<td headers="m1natwt_rep22" class="gt_row gt_right">95.96693</td>
<td headers="m1natwt_rep23" class="gt_row gt_right">97.10217</td>
<td headers="m1natwt_rep24" class="gt_row gt_right">101.69630</td>
<td headers="m1natwt_rep25" class="gt_row gt_right">99.66428</td>
<td headers="m1natwt_rep26" class="gt_row gt_right">101.72647</td>
<td headers="m1natwt_rep27" class="gt_row gt_right">96.58415</td>
<td headers="m1natwt_rep28" class="gt_row gt_right">95.98499</td>
<td headers="m1natwt_rep29" class="gt_row gt_right">100.43622</td>
<td headers="m1natwt_rep30" class="gt_row gt_right">0.00000</td>
<td headers="m1natwt_rep31" class="gt_row gt_right">105.47424</td>
<td headers="m1natwt_rep32" class="gt_row gt_right">96.22710</td>
<td headers="m1natwt_rep33" class="gt_row gt_right">95.11009</td>
<td headers="informal_support_prop" class="gt_row gt_right">1</td>
<td headers="informal_support_max" class="gt_row gt_right">3</td>
<td headers="informal_support_binary" class="gt_row gt_right">1</td>
<td headers="informal_support_ordinal" class="gt_row gt_center">3</td>
<td headers="IPV_prop" class="gt_row gt_right">0.08333333</td>
<td headers="IPV_max" class="gt_row gt_right">25</td>
<td headers="IPV_binary" class="gt_row gt_right">1</td>
<td headers="IPV_ordinal" class="gt_row gt_center">2</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<p>We’ll need to run two models — the first predicting the mediator, the second predicting the outcome — and feed these models into <code>mediation::mediate()</code>.</p>
<section id="issue-1-correctly-applying-the-fragile-families-weights" class="level2">
<h2 class="anchored" data-anchor-id="issue-1-correctly-applying-the-fragile-families-weights">Issue 1: Correctly applying the Fragile Families weights</h2>
<p>We fit the models using <code>survey::svyglm</code> in order to be able to take the weights into account. First, we need to tell <code>survey</code> that our data is weighted, which we do with the help of the <code>srvyr</code> package for tidyverse-like convenience. Our first attempt looked like this:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat_weights <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  srvyr<span class="sc">::</span><span class="fu">as_survey_rep</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">repweights =</span> dplyr<span class="sc">::</span><span class="fu">contains</span>(<span class="st">"_rep"</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> m1natwt,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">combined_weights =</span> <span class="cn">TRUE</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>However, coming across this <a href="https://stats.stackexchange.com/questions/409463/duplicating-stata-survey-design-using-svrepdesign-from-survey-package-in-r">CrossValidated question</a> and confirming with the Fragile Families guide to using the weights showed us that the code above fails to tell <code>survey</code> that we want to use jackknife variance estimation. From the <a href="https://fragilefamilies.princeton.edu/sites/fragilefamilies/files/using_the_fragile_families_weights_waves_1_6.pdf">guide (PDF)</a>, p.&nbsp;2:</p>
<blockquote class="blockquote">
<p>As described in the weights construction memo, the replicate weights require using jackknife estimation of standard errors.</p>
</blockquote>
<p>Woops.</p>
<p>So, to properly apply the weights, we run this code block instead:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dat_weights <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  srvyr<span class="sc">::</span><span class="fu">as_survey_rep</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">repweights =</span> dplyr<span class="sc">::</span><span class="fu">contains</span>(<span class="st">"_rep"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> m1natwt,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">combined_weights =</span> <span class="cn">TRUE</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">"JKn"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">scales =</span> <span class="dv">1</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">rscales =</span> <span class="dv">1</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mse =</span> <span class="cn">TRUE</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="running-the-weighted-models-and-mediation" class="level1">
<h1>Running the weighted models and mediation</h1>
<p>With the weighted dataframe in hand, we can use <code>survey::svyglm</code> to fit our GLMs predicting <code>informal_support</code> and <code>IPV</code>.</p>
<p>Our informal support variable is the sum of three items for which each mother could get a 1 or a 0 (indicating that she did or did not have access to that form of support). As such, it seems sensible to model it as a binomial outcome — each mother has a certain number of “successes” out of three possible trials.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>model_m_1 <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_prop <span class="sc">~</span> race,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> informal_support_max,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_m_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survey::svyglm(formula = informal_support_prop ~ race, weights = informal_support_max, 
    design = dat_weights, family = "binomial")

Survey design:
Called via srvyr

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.6891     0.2778   13.28 2.48e-14 ***
raceBlack    -1.7317     0.3972   -4.36 0.000133 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1299.299)

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>We get the following warning many times:</p>
<pre><code>Warning: non-integer #successes in a binomial glm!</code></pre>
<p>This is <code>survey</code>’s way of asking us to specify the family as “quasibinomial” instead of “binomial”, since our outcome is a proportion (weighted by the number of trials) and not binary. However, if we do that, <code>mediation</code> will not work with our models.</p>
<p>Our IPV variable is the sum of twelve items for which each mother could get a score of 0, 1, or 2 (indicating how often she experienced a given form of violence from her partner). As such, it also seems sensible to model it as a binomial outcome — each mother has a certain number of “successes” out of 24 possible “trials”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>model_y_1 <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_prop <span class="sc">~</span> race <span class="sc">+</span> informal_support_prop,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> IPV_max,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_y_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survey::svyglm(formula = IPV_prop ~ race + informal_support_prop, 
    weights = IPV_max, design = dat_weights, family = "binomial")

Survey design:
Called via srvyr

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            -1.4968     0.2949  -5.075 1.89e-05 ***
raceBlack               0.1207     0.1680   0.719  0.47794    
informal_support_prop  -0.7482     0.2678  -2.794  0.00899 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 291.4434)

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>(Here again we suppressed the warning that would have otherwise popped up.)</p>
<p>Finally, our mediation:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>med_1 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_1,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_1,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_prop"</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>weights taken as sampling weights, not total number of trials</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mediation::mediate(model.m = model_m_1, model.y = model_y_1, :
treatment and control values do not match factor levels; using White and Black
as control and treatment, respectively</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value   
ACME (control)            0.00938      0.00108         0.02    0.01 **
ACME (treated)            0.00999      0.00122         0.03    0.01 **
ADE (control)             0.01062     -0.02048         0.04    0.50   
ADE (treated)             0.01123     -0.02186         0.04    0.50   
Total Effect              0.02061     -0.01070         0.05    0.20   
Prop. Mediated (control)  0.33912     -3.62170         3.72    0.21   
Prop. Mediated (treated)  0.38715     -3.38640         3.41    0.21   
ACME (average)            0.00969      0.00114         0.03    0.01 **
ADE (average)             0.01092     -0.02124         0.04    0.50   
Prop. Mediated (average)  0.36313     -3.49597         3.54    0.21   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 1000 </code></pre>
</div>
</div>
<p>A small but statistically significant mediation effect! The warning about weights not being taken as total number of trials makes us nervous, but then again, we did give the models sampling weights, so maybe it’s ok?</p>
<section id="issue-2-mediation-with-multiple-trial-binomial-mediator-runs-for-weighted-but-not-for-unweighted-models" class="level2">
<h2 class="anchored" data-anchor-id="issue-2-mediation-with-multiple-trial-binomial-mediator-runs-for-weighted-but-not-for-unweighted-models">Issue 2: Mediation with “multiple-trial binomial mediator” runs for weighted but not for unweighted models?</h2>
<p>We knew that we would eventually perform a sensitivity analysis where all models would be run without using the sampling weights. Running the previous steps with the <code>glm</code> command resulted in an issue:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model_m_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_prop <span class="sc">~</span> race,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> informal_support_max,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>model_y_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_prop <span class="sc">~</span> race <span class="sc">+</span> informal_support_prop,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> IPV_max,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>med_2 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_2,</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_2,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_prop"</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in mediation::mediate(model.m = model_m_2, model.y = model_y_2, : weights on outcome and mediator models not identical</code></pre>
</div>
</div>
<p>It seems like <code>mediation::mediate</code> is taking the weights we pass to the GLM function (which correspond to total number of trials, not to sampling weights) as sampling weights, and complaining when it notices that these weights are not the same for the mediator and outcome models. Vasco perhaps clumsily posted this as an <a href="https://github.com/kosukeimai/mediation/issues/59">issue on the mediation package Github</a>, but at least for now there has been no answer. We can work around this by using an alternative way of specifying the same GLM model — instead of using a proportion as an outcome and passing the number of trials through the <code>weights</code> argument, we can instead use a vector of “successes” and “failures” (which corresponds to the total number of trials minus the number of successes) as the outcome:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model_m_2<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">cbind</span>(informal_support, informal_support_max <span class="sc">-</span> informal_support) <span class="sc">~</span> race,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>model_y_2<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">cbind</span>(IPV, IPV_max <span class="sc">-</span> IPV) <span class="sc">~</span> race <span class="sc">+</span> informal_support_prop,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>med_2<span class="fl">.1</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_2<span class="fl">.1</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_2<span class="fl">.1</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_prop"</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_2<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value    
ACME (control)            0.00303      0.00163         0.00  &lt;2e-16 ***
ACME (treated)            0.00334      0.00181         0.01  &lt;2e-16 ***
ADE (control)             0.01296      0.00723         0.02  &lt;2e-16 ***
ADE (treated)             0.01327      0.00739         0.02  &lt;2e-16 ***
Total Effect              0.01630      0.01048         0.02  &lt;2e-16 ***
Prop. Mediated (control)  0.18553      0.09806         0.34  &lt;2e-16 ***
Prop. Mediated (treated)  0.20474      0.10918         0.35  &lt;2e-16 ***
ACME (average)            0.00319      0.00173         0.00  &lt;2e-16 ***
ADE (average)             0.01312      0.00732         0.02  &lt;2e-16 ***
Prop. Mediated (average)  0.19513      0.10342         0.35  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 1000 </code></pre>
</div>
</div>
<p>Success! But at the cost of suspicion. The <a href="https://www.rdocumentation.org/packages/mediation/versions/4.5.0/topics/mediate">documentation for the <code>mediate</code> function</a> warns us that (emphasis added):</p>
<blockquote class="blockquote">
<p>As of version 4.0, the mediator model can be of either ‘lm’, ‘glm’ (or `bayesglm’), ‘polr’ (or `bayespolr’), ‘gam’, ‘rq’, `survreg’, or `merMod’ class, corresponding respectively to the linear regression models, generalized linear models, ordered response models, generalized additive models, quantile regression models, parametric duration models, or multilevel models.. For binary response models, the ‘mediator’ must be a numeric variable with values 0 or 1 as opposed to a factor. Quasi-likelihood-based inferences are not allowed for the mediator model because the functional form must be exactly specified for the estimation algorithm to work. <strong>The ‘binomial’ family can only be used for binary response mediators and cannot be used for multiple-trial responses</strong>. This is due to conflicts between how the latter type of models are implemented in <a href="https://www.rdocumentation.org/link/glm?package=mediation&amp;version=4.5.0"><strong><code>glm</code></strong></a> and how ‘mediate’ is currently written.</p>
</blockquote>
<p>Thus, until the package author clarifies whether this implementation results in correct estimates, we are cautious about trusting them.</p>
<section id="sanity-check-comparing-results-with-linear-probability-models" class="level3">
<h3 class="anchored" data-anchor-id="sanity-check-comparing-results-with-linear-probability-models">Sanity check: comparing results with linear probability models</h3>
<p>As a sanity check, to become a little more confident that <code>mediate</code> is working as intended even though it’s not supposed to work well with a multiple-trial binomial mediator, we compare the results of our model that did run (<code>med_2.1</code>) with a mediation run on linear probability models (basically, using <code>lm()</code> instead of <code>glm()</code> even though the outcomes are proportions.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model_m_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_prop <span class="sc">~</span> race,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>model_y_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_prop <span class="sc">~</span> race <span class="sc">+</span> informal_support_prop,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>med_2<span class="fl">.2</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_2<span class="fl">.2</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_2<span class="fl">.2</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_prop"</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_2<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

               Estimate 95% CI Lower 95% CI Upper p-value    
ACME            0.00318      0.00155         0.01  &lt;2e-16 ***
ADE             0.01376      0.00209         0.03   0.024 *  
Total Effect    0.01694      0.00502         0.03   0.006 ** 
Prop. Mediated  0.18625      0.07521         0.63   0.006 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 1000 </code></pre>
</div>
</div>
<p>The results seem fairly similar, but this provides limited comfort.</p>
</section>
<section id="bonus-finding-you-can-specify-a-mediator-that-is-not-technically-the-variable-that-your-mediator-model-predicts" class="level3">
<h3 class="anchored" data-anchor-id="bonus-finding-you-can-specify-a-mediator-that-is-not-technically-the-variable-that-your-mediator-model-predicts">Bonus finding: you can specify a mediator that is not technically the variable that your mediator model predicts</h3>
<p>Note that in the models used for <code>med_2.1</code> there is a potential discrepancy. The mediator model is formulated as <code>formula = cbind(informal_support, informal_support_max - informal_support) ~ race</code>, while the outcome model is formulated as <code>formula = cbind(IPV, IPV_max - IPV) ~ race + informal_support_prop</code>. So the outcome model is using <code>informal_support_prop</code> (our intended mediator) as a predictor of IPV, but the mediator model uses the variables <code>informal_support</code> and <code>informal_support_max</code> to internally generate the proportion of successes. In the call to <code>mediation::mediate</code> we can then specify <code>mediator = "informal_support_prop"</code>, and all seems to work as intended. What if we used <code>informal_support</code> as predictor in the outcome model instead? We can then specify <code>mediator = "informal_support"</code> and end up with something like this:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model_m_2<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">cbind</span>(informal_support, informal_support_max <span class="sc">-</span> informal_support) <span class="sc">~</span> race,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>model_y_2<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">cbind</span>(IPV, IPV_max <span class="sc">-</span> IPV) <span class="sc">~</span> race <span class="sc">+</span> informal_support,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>med_2<span class="fl">.3</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_2<span class="fl">.3</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_2<span class="fl">.3</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support"</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_2<span class="fl">.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value    
ACME (control)           0.001154     0.000572         0.00  &lt;2e-16 ***
ACME (treated)           0.001265     0.000635         0.00  &lt;2e-16 ***
ADE (control)            0.017330     0.009599         0.02  &lt;2e-16 ***
ADE (treated)            0.017441     0.009655         0.02  &lt;2e-16 ***
Total Effect             0.018595     0.010865         0.03  &lt;2e-16 ***
Prop. Mediated (control) 0.062094     0.029240         0.12  &lt;2e-16 ***
Prop. Mediated (treated) 0.067743     0.032533         0.13  &lt;2e-16 ***
ACME (average)           0.001209     0.000606         0.00  &lt;2e-16 ***
ADE (average)            0.017386     0.009627         0.02  &lt;2e-16 ***
Prop. Mediated (average) 0.064918     0.030932         0.13  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 1000 </code></pre>
</div>
</div>
<p>Looking at the last three rows (Average Causal Mediated Effect (average), Average Direct Effect (average), and Proportion Mediated (average)), the results seem different than the ones estimated in <code>med_2.1</code> (which used <code>informal_support_prop</code> as mediator) and <code>med.2.2</code> (which used linear proability models). But looking closer, you’ll notice that the estimates related to the mediator, namely of the Average Causal Mediated Effect and the Proportion Mediated just seem to be divided by three!</p>
<p>My assumption about how that came to be: When we use <code>informal_support_prop</code>, which can only take values on the <span class="math inline">\((0, 1)\)</span> interval, the ACME estimates correspond to the change in probability of IPV associated with going from 0 to 1 on the mediator and thus span the full range of the mediator. When we use <code>informal_support</code>, which takes values in the set <span class="math inline">\(\{0, 1, 2, 3\}\)</span>, the estimates also correspond to the increase in probability of IPV associated with an increase of 1 on the mediator (e.g., from 0 to 1), but this is only <span class="math inline">\(\frac{1}{3}\)</span> of the total possible way. Thus, applying this effect three times would be equivalent to moving from 0 to 3 on the mediator scale, the same as moving from 0 to 1 when the mediator is a proportion.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</section>
</section>
<section id="issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified" class="level2">
<h2 class="anchored" data-anchor-id="issue-3-using-a-binary-mediator-and-a-binomial-outcome-works-with-cbindsuccesses-failures-but-not-with-proportion-as-outcome-and-weights-argument-specified">Issue 3: Using a binary mediator and a binomial outcome — works with cbind(successes, failures) but not with proportion as outcome and weights argument specified</h2>
<p>Next, we attempted to run everything with the same binomial outcome and a binary mediator.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model_m_3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_binary <span class="sc">~</span> race,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>model_y_3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_prop <span class="sc">~</span> race <span class="sc">+</span> informal_support_binary,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> IPV_max,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>med_3 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_3,</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_3,</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in mediation::mediate(model.m = model_m_3, model.y = model_y_3, : weights on outcome and mediator models not identical</code></pre>
</div>
</div>
<p>Once again we find that <code>mediate</code> complains about different weights on mediator and outcome models, even though, according to the documentation, it works with a binary mediator and a binomial outcome. We then try using the vector of successes and failures specification for the outcome model:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model_y_3<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">cbind</span>(IPV, IPV_max <span class="sc">-</span> IPV) <span class="sc">~</span> race <span class="sc">+</span> informal_support_binary,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>med_3<span class="fl">.1</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_3,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_3<span class="fl">.1</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_3<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value    
ACME (control)            0.00347      0.00148         0.01  &lt;2e-16 ***
ACME (treated)            0.00382      0.00165         0.01  &lt;2e-16 ***
ADE (control)             0.01230      0.00689         0.02  &lt;2e-16 ***
ADE (treated)             0.01265      0.00713         0.02  &lt;2e-16 ***
Total Effect              0.01612      0.01022         0.02  &lt;2e-16 ***
Prop. Mediated (control)  0.21348      0.09638         0.37  &lt;2e-16 ***
Prop. Mediated (treated)  0.23682      0.10663         0.40  &lt;2e-16 ***
ACME (average)            0.00364      0.00157         0.01  &lt;2e-16 ***
ADE (average)             0.01247      0.00702         0.02  &lt;2e-16 ***
Prop. Mediated (average)  0.22515      0.10153         0.38  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 1000 </code></pre>
</div>
</div>
<p>This approach runs, but we are still left wondering whether we can trust the estimates.</p>
</section>
<section id="issue-4-ordinal-mediator-and-binomial-outcome-dont-work-together." class="level2">
<h2 class="anchored" data-anchor-id="issue-4-ordinal-mediator-and-binomial-outcome-dont-work-together.">Issue 4: Ordinal mediator and binomial outcome don’t work together.</h2>
<p>Because we would prefer not to binarize the social support variable in order to keep all the information that we can, we also explored using an ordinal mediator model. <code>mediate()</code> works with ordinal models fit with <code>MASS::polr</code>, so we attempted that.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model_m_4 <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">polr</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_ordinal <span class="sc">~</span> race,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Hess =</span> <span class="cn">TRUE</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>model_y_4 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">cbind</span>(IPV, IPV_max <span class="sc">-</span> IPV) <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>med_4 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_4,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_4,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in UseMethod("isSymmetric"): no applicable method for 'isSymmetric' applied to an object of class "c('double', 'numeric')"</code></pre>
</div>
</div>
<p>The first issue arises, but it’s easy to fix. Again, from the <a href="https://rdrr.io/cran/mediation/man/mediate.html">documentation of the mediate function</a>:</p>
<blockquote class="blockquote">
<p>The quasi-Bayesian approximation (King et al.&nbsp;2000) cannot be used if ‘model.m’ is of class ‘rq’ or ‘gam’, or if ‘model.y’ is of class ‘gam’, ‘polr’ or ‘bayespolr’. In these cases, either an error message is returned or use of the nonparametric bootstrap is forced. Users should note that use of the nonparametric bootstrap often requires significant computing time, especially when ‘sims’ is set to a large value.</p>
</blockquote>
<p>We can get around this by setting the argument <code>boot</code> to <code>TRUE</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>med_4 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_4,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_4,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in cbind(IPV, IPV_max - IPV): object 'IPV' not found</code></pre>
</div>
</div>
<p>Now we get a different problem. It seems the <code>boot</code> package is having trouble with the way we set up our outcome model — hopefully using the other implementation will take care of that.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model_y_4<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_prop <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> IPV_max,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>med_4 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_4,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_4<span class="fl">.1</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span>,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in mediation::mediate(model.m = model_m_4, model.y = model_y_4.1, : weights on outcome and mediator models not identical</code></pre>
</div>
</div>
<p>Finally, we reach a dead-end. It seems once again the <code>mediate</code> function is taking the prior weights we fed into our <code>glm</code> as sample weight and complaining that our ordinal model doesn’t have the same sample weights. If we are willing to throw away some information, we can make it all work with a binary outcome, thusly:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model_y_4<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_binary <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>med_4 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_4,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_4<span class="fl">.2</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

                          Estimate 95% CI Lower 95% CI Upper p-value  
ACME (control)            0.003754    -0.000532         0.01   0.080 .
ACME (treated)            0.003648    -0.000537         0.01   0.084 .
ADE (control)             0.012588    -0.031049         0.06   0.558  
ADE (treated)             0.012482    -0.030895         0.06   0.558  
Total Effect              0.016236    -0.025388         0.06   0.456  
Prop. Mediated (control)  0.231212    -1.600398         1.73   0.480  
Prop. Mediated (treated)  0.224694    -1.624927         1.74   0.484  
ACME (average)            0.003701    -0.000532         0.01   0.082 .
ADE (average)             0.012535    -0.030972         0.06   0.558  
Prop. Mediated (average)  0.227953    -1.610809         1.73   0.482  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 1000 </code></pre>
</div>
</div>
<p>This runs, although the bootstrap adds significantly to computing time and we had to binarize IPV to achieve it.</p>
</section>
<section id="issue-5-reconciling-svyglm-and-svyolr-models" class="level2">
<h2 class="anchored" data-anchor-id="issue-5-reconciling-svyglm-and-svyolr-models">Issue 5: Reconciling svyglm() and svyolr() models</h2>
<p>With this partial success, we checked to see if we could also run this latest mediation on the weighted data.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model_m_5 <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyolr</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_ordinal <span class="sc">~</span> race,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in optim(s0, fmin, gmin, method = "BFGS", ...): initial value in 'vmmin' is not finite</code></pre>
</div>
</div>
<p>This throws an error, which <a href="https://stackoverflow.com/questions/28916377/r-error-with-polr-initial-value-in-vmmin-is-not-finite?rq=2">this StackOverflow post</a> can help us solve. We can help the function by providing plausible start values for the coefficients and the intercepts/thresholds. We have one coefficient and three thresholds (from 0 to 1, from 1 to 2, and from 2 to 3), and we know they should be relatively close to zero as well as that the thresholds should be in ascending order. With the syntax <code>start = c(coefficients, thresholds)</code> we can make it work:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model_m_5 <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyolr</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_ordinal <span class="sc">~</span> race,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_m_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
svyolr(formula = informal_support_ordinal ~ race, design = dat_weights, 
    start = c(0, -1, 0, 1))

Coefficients:
             Value Std. Error  t value
raceBlack -1.62481  0.3874065 -4.19407

Intercepts:
    Value    Std. Error t value 
0|1  -4.5463   0.3580   -12.6979
1|2  -3.7384   0.2741   -13.6376
2|3  -3.0236   0.2458   -12.3027</code></pre>
</div>
</div>
<p>Ok, moving on.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>model_y_5 <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_binary <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>med_5 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_5,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_5,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span>,</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in mediation::mediate(model.m = model_m_5, model.y = model_y_5, : weights on outcome and mediator models not identical</code></pre>
</div>
</div>
<p>Not this again 😭. We knew that the weights used for the <code>svyglm()</code> and <code>svyolr()</code> models were the same, so there must be something else happening in the background. Vasco did some investigating and again <a href="https://stackoverflow.com/questions/76900094/inconsistent-weights-with-lumleys-survey-package-svyglm-vs-svyolr-error-or-b">turned to Stack Overflow</a>. We can see what weights are stored in the model objects generated by <code>svyglm()</code> and <code>svyolr()</code> using the <code>model.frame()</code> function. In the following two code blocks we also use <code>dplyr::slice_head()</code> to display just the first line of results output by <code>model.frame().</code></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.frame</span>(model_m_5) <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">slice_head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  informal_support_ordinal  race (weights)
1                        3 Black  41.13614</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.frame</span>(model_y_5) <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">slice_head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  IPV_binary  race informal_support_ordinal (weights)
1          1 Black                        3 0.1142592</code></pre>
</div>
</div>
<p>The first weight for our ordinal model appears to be 41.13614, while the binomial model uses 0.1142592. We can extract all the weights for both models and compare them. Let’s look at their ratio.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>weight_comparison <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">binomial_weights =</span> <span class="fu">model.frame</span>(model_y_5)<span class="sc">$</span><span class="st">`</span><span class="at">(weights)</span><span class="st">`</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordinal_weights =</span> <span class="fu">model.frame</span>(model_m_5)<span class="sc">$</span><span class="st">`</span><span class="at">(weights)</span><span class="st">`</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight_quotient =</span> binomial_weights <span class="sc">/</span> ordinal_weights</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>weight_comparison <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  binomial_weights ordinal_weights weight_quotient
             &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
1           0.114             41.1         0.00278
2           0.0555            20.0         0.00278
3           0.0340            12.2         0.00278
4           0.338            122.          0.00278
5           0.239             86.0         0.00278</code></pre>
</div>
</div>
<p>Would you look at that! The ratio seems to be constant. We can check the entire <code>weight_quotient</code> column just to be extra sure:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>weight_comparison <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">count</span>(weight_quotient)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  weight_quotient     n
            &lt;dbl&gt; &lt;int&gt;
1         0.00278   218
2         0.00278  1733
3         0.00278     4</code></pre>
</div>
</div>
<p>There seem to be three different values that all look the same — perhaps this will make more sense once we learn more about floating point arithmetic, but for now we’ll say the ratio between the weights is always the same. On Stack Overflow, Thomas Lumley, maintainer of the <code>survey</code> package, explains in a reply to my post:</p>
<blockquote class="blockquote">
<p>Some functions in the survey package rescale the weights to have unit mean because the large weights (thousands or tens of thousands) in some national surveys can cause convergence problems.</p>
<p>Since the results aren’t affected at all, the <code>mediate</code> package could probably work around this fairly easily. However, there’s a <code>rescale=FALSE</code> option to <code>svyglm</code> to not rescale the weights, provided for this sort of purpose.</p>
<p>If you then have convergence problems in <code>svyglm</code> you could manually rescale the weights to have unit mean before doing any of the analyses.</p>
</blockquote>
<p>Good to know!</p>
<p>Let’s set <code>rescale = FALSE</code> in the <code>svyglm</code> model and try our luck:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>model_y_5<span class="fl">.1</span> <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_binary <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">rescale =</span> <span class="cn">FALSE</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in is.data.frame(pwts): object 'pwts' not found</code></pre>
</div>
</div>
<p>This is perplexing, but <a href="https://stackoverflow.com/questions/66465401/error-with-svyglm-function-in-survey-package-in-r-all-variables-must-be-in-des">someone else on Stack Overflow</a> a couple of years ago encountered a similar problem, where object “.survey.prob.weights” was not found when <code>rescale</code> was set to <code>FALSE</code>. After looking at the <a href="https://rdrr.io/rforge/survey/src/R/surveyrep.R">source code</a> and the <a href="https://stackoverflow.com/a/66474985/12296038">accepted answer by user xilliam</a> to the Stack Overflow post, we try to assign the prior weights contained in the survey design object to an object named <code>pwts</code> in the global environment, and that makes <code>svyglm()</code> happy again.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>pwts <span class="ot">&lt;-</span> dat_weights<span class="sc">$</span>pweights</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>model_y_5<span class="fl">.1</span> <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_binary <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">rescale =</span> <span class="cn">FALSE</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="co"># remove pwts from the global environment</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="st">"pwts"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>However, we can’t be sure if this correctly solves the problem or introduces new errors. To ask the package maintainer (or anyone else who might know) more directly, Vasco posed this problem in a new Stack Overflow post. XXX LINK MISSING</p>
<p>Now we try to run the mediation.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>med_5 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_5,</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_5<span class="fl">.1</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in MASS::polr(formula, data = df, ..., Hess = TRUE, model = FALSE, : formal argument "data" matched by multiple actual arguments</code></pre>
</div>
</div>
<p>Somehow it is not working again. What if the outcome model was ordinal as well, just for fun?</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>model_y_5<span class="fl">.2</span> <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyolr</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_ordinal <span class="sc">~</span> race <span class="sc">+</span> informal_support_ordinal,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">24</span>))</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>med_5 <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_5,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_5<span class="fl">.2</span>,</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> n_sims,</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_ordinal"</span>,</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in MASS::polr(formula, data = df, ..., Hess = TRUE, model = FALSE, : formal argument "data" matched by multiple actual arguments</code></pre>
</div>
</div>
<p>Ok, we give up here.</p>
</section>
<section id="issue-6-options-and-choices-to-boot-to-robustse-or-not-to-robustse" class="level2">
<h2 class="anchored" data-anchor-id="issue-6-options-and-choices-to-boot-to-robustse-or-not-to-robustse">Issue 6: Options and choices to boot — To robustSE or not to robustSE?</h2>
<p>For now, we’ve ignored an optional setting to <code>mediate()</code>: the <code>robustSE</code> argument defaults to <code>FALSE</code>, and, according to <a href="https://www.rdocumentation.org/packages/mediation/versions/4.5.0/topics/mediate">the documentation</a>, “If ‘TRUE’, heteroskedasticity-consistent standard errors will be used in quasi-Bayesian simulations. Ignored if ‘boot’ is ‘TRUE’ or neither ‘model.m’ nor ‘model.y’ has a method for <strong><code>vcovHC</code></strong> in the <strong><code>sandwich</code></strong> package.” So we have three options:</p>
<ol type="1">
<li><code>boot = TRUE</code> and, automatically, <code>robustSE = FALSE</code></li>
<li><code>boot = FALSE</code> and <code>robustSE = TRUE</code>, and</li>
<li><code>boot = FALSE</code> and <code>robustSE = FALSE</code>.</li>
</ol>
<p>And we know that, when chosen, the heteroskedasticity-consistent standard errors will be calculated with the help of the <code>sandwich</code> package.</p>
<p>According to the <code>mediation</code> package <a href="https://cran.r-project.org/web/packages/mediation/vignettes/mediation.pdf">vignettes</a>, the authors recommend setting <code>boot = TRUE</code>: “In general, as long as computing power is not an issue, analysts should estimate confidence intervals via the bootstrap with more than 1000 resamples, which is the default number of simulations.” So we could do that. Unfortunately, computing power <em>is</em> an issue, as we wanted to run a multiverse analysis that meant we would use the <code>mediate()</code> function a bunch of times. To figure out whether to set <code>robustSE</code> to <code>TRUE</code> or <code>FALSE</code>, it could be useful to see which option gives use results that are closer to the bootstrap option. Let’s use a binary mediator and outcome, just so we are sure there aren’t other issues at play.</p>
<p>First, we compare unweighted models. To reduce simulation-dependent variability, we set <code>sims = 3000</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>model_m_6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_binary <span class="sc">~</span> race,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>model_y_6 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_binary <span class="sc">~</span> race <span class="sc">+</span> informal_support_binary,</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat,</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>med_6<span class="fl">.1</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_6,</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_6,</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> <span class="dv">3000</span>,</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>med_6<span class="fl">.2</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_6,</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_6,</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> <span class="dv">3000</span>,</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">robustSE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a>med_6<span class="fl">.3</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_6,</span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_6,</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> <span class="dv">3000</span>,</span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">robustSE =</span> <span class="cn">FALSE</span>,</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_6<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

                          Estimate 95% CI Lower 95% CI Upper p-value  
ACME (control)            4.26e-03    -1.03e-04         0.01   0.058 .
ACME (treated)            4.17e-03    -9.62e-05         0.01   0.058 .
ADE (control)             1.07e-02    -3.14e-02         0.05   0.624  
ADE (treated)             1.06e-02    -3.11e-02         0.05   0.624  
Total Effect              1.49e-02    -2.76e-02         0.06   0.491  
Prop. Mediated (control)  2.86e-01    -2.09e+00         2.67   0.519  
Prop. Mediated (treated)  2.80e-01    -2.12e+00         2.69   0.519  
ACME (average)            4.22e-03    -9.96e-05         0.01   0.058 .
ADE (average)             1.07e-02    -3.13e-02         0.05   0.624  
Prop. Mediated (average)  2.83e-01    -2.10e+00         2.68   0.519  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_6<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                          Estimate 95% CI Lower 95% CI Upper p-value  
ACME (control)            0.004033    -0.000136         0.01   0.055 .
ACME (treated)            0.003953    -0.000126         0.01   0.055 .
ADE (control)             0.010844    -0.030717         0.05   0.599  
ADE (treated)             0.010763    -0.030663         0.05   0.599  
Total Effect              0.014797    -0.026951         0.06   0.469  
Prop. Mediated (control)  0.132980    -2.067129         2.95   0.495  
Prop. Mediated (treated)  0.124956    -2.081693         2.97   0.495  
ACME (average)            0.003993    -0.000131         0.01   0.055 .
ADE (average)             0.010804    -0.030690         0.05   0.599  
Prop. Mediated (average)  0.128968    -2.075434         2.96   0.495  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_6<span class="fl">.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                          Estimate 95% CI Lower 95% CI Upper p-value  
ACME (control)            0.004049    -0.000285         0.01   0.065 .
ACME (treated)            0.003965    -0.000274         0.01   0.065 .
ADE (control)             0.011725    -0.029570         0.05   0.587  
ADE (treated)             0.011641    -0.029372         0.05   0.587  
Total Effect              0.015690    -0.024297         0.06   0.450  
Prop. Mediated (control)  0.129482    -2.343357         2.62   0.479  
Prop. Mediated (treated)  0.121884    -2.368626         2.64   0.479  
ACME (average)            0.004007    -0.000279         0.01   0.065 .
ADE (average)             0.011683    -0.029461         0.05   0.587  
Prop. Mediated (average)  0.125683    -2.351094         2.63   0.479  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
</div>
<p>We can see that the results are very similar, and in fact running the mediations several times reveals that the difference seems to be due to simulation variability. Given this, Vasco would personally rather specify <code>robustSE = FALSE</code>, since it does not make sense to correct for heteroskedasticity in a logistic regression model which <em>cannot suffer from</em> heteroskedasticity in the first place.</p>
<p>What about if we use weighted models?</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>model_m_6<span class="fl">.1</span> <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> informal_support_binary <span class="sc">~</span> race,</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>model_y_6<span class="fl">.1</span> <span class="ot">&lt;-</span> survey<span class="sc">::</span><span class="fu">svyglm</span>(</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> IPV_binary <span class="sc">~</span> race <span class="sc">+</span> informal_support_binary,</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> dat_weights,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>med_6<span class="fl">.4</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_6<span class="fl">.1</span>,</span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_6<span class="fl">.1</span>,</span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> <span class="dv">3000</span>,</span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">boot =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a>med_6<span class="fl">.5</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_6<span class="fl">.1</span>,</span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_6<span class="fl">.1</span>,</span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> <span class="dv">3000</span>,</span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">robustSE =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-30"><a href="#cb63-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-31"><a href="#cb63-31" aria-hidden="true" tabindex="-1"></a>med_6<span class="fl">.6</span> <span class="ot">&lt;-</span> mediation<span class="sc">::</span><span class="fu">mediate</span>(</span>
<span id="cb63-32"><a href="#cb63-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.m =</span> model_m_6<span class="fl">.1</span>,</span>
<span id="cb63-33"><a href="#cb63-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">model.y =</span> model_y_6<span class="fl">.1</span>,</span>
<span id="cb63-34"><a href="#cb63-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">sims =</span> <span class="dv">3000</span>,</span>
<span id="cb63-35"><a href="#cb63-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">robustSE =</span> <span class="cn">FALSE</span>,</span>
<span id="cb63-36"><a href="#cb63-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">treat =</span> <span class="st">"race"</span>,</span>
<span id="cb63-37"><a href="#cb63-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">mediator =</span> <span class="st">"informal_support_binary"</span></span>
<span id="cb63-38"><a href="#cb63-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-39"><a href="#cb63-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-40"><a href="#cb63-40" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_6<span class="fl">.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Nonparametric Bootstrap Confidence Intervals with the Percentile Method

                         Estimate 95% CI Lower 95% CI Upper p-value    
ACME (control)            0.01439      0.00993         0.02  &lt;2e-16 ***
ACME (treated)            0.01344      0.00927         0.02  &lt;2e-16 ***
ADE (control)             0.02845      0.02822         0.03  &lt;2e-16 ***
ADE (treated)             0.02750      0.02711         0.03  &lt;2e-16 ***
Total Effect              0.04189      0.03761         0.05  &lt;2e-16 ***
Prop. Mediated (control)  0.34350      0.26424         0.43  &lt;2e-16 ***
Prop. Mediated (treated)  0.32093      0.24687         0.40  &lt;2e-16 ***
ACME (average)            0.01392      0.00960         0.02  &lt;2e-16 ***
ADE (average)             0.02798      0.02773         0.03  &lt;2e-16 ***
Prop. Mediated (average)  0.33221      0.25555         0.41  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_6<span class="fl">.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value    
ACME (control)            0.01508      0.00994         0.02  &lt;2e-16 ***
ACME (treated)            0.01410      0.00929         0.02  &lt;2e-16 ***
ADE (control)             0.02826      0.01438         0.04  0.0013 ** 
ADE (treated)             0.02727      0.01390         0.04  0.0013 ** 
Total Effect              0.04236      0.02760         0.06  &lt;2e-16 ***
Prop. Mediated (control)  0.35565      0.23977         0.53  &lt;2e-16 ***
Prop. Mediated (treated)  0.33217      0.21900         0.51  &lt;2e-16 ***
ACME (average)            0.01459      0.00962         0.02  &lt;2e-16 ***
ADE (average)             0.02776      0.01414         0.04  0.0013 ** 
Prop. Mediated (average)  0.34391      0.22950         0.52  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(med_6<span class="fl">.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value
ACME (control)            0.01477     -0.00647         0.04    0.17
ACME (treated)            0.01402     -0.00621         0.04    0.17
ADE (control)             0.02857     -0.08888         0.15    0.66
ADE (treated)             0.02782     -0.08453         0.14    0.66
Total Effect              0.04259     -0.07338         0.16    0.48
Prop. Mediated (control)  0.15913     -2.46718         2.69    0.56
Prop. Mediated (treated)  0.12961     -2.62920         2.78    0.56
ACME (average)            0.01440     -0.00627         0.04    0.17
ADE (average)             0.02820     -0.08676         0.14    0.66
Prop. Mediated (average)  0.14437     -2.55170         2.76    0.56

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
</div>
<p>While the estimates are similar, the confidence intervals are <em>much</em> tighter when <code>boot</code> or <code>robustSE</code> are set to <code>TRUE</code>, and suddenly all estimates are significant! What gives?</p>
<p>First, an <a href="https://stackoverflow.com/a/75128332/12296038">answer by Thomas Lumley</a> (maintainer of the <code>survey</code> package) on Stack Overflow suggests that bootstrapping doesn’t work well with these survey-weighted models, although his answer does not fully map to our situation. In <a href="https://stackoverflow.com/a/56317510/12296038">another answer</a>, this time about applying robust standard errors with the <code>sandwich</code> package<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, Lumley is clearer: “For <code>svyglm</code> models, <code>vcov()</code> already produces the appropriate sandwich estimator, and I don’t think the”sandwich” package knows enough about the internals of the object to get it right.” A few years prior, Achim Zeileis, maintainer of the <code>sandwich</code> package, had given <a href="https://stackoverflow.com/a/28840854/12296038">a different perspective</a> which also boils down to <strong>do not use <code>sandwich</code></strong> <strong>on models fit with <code>survey</code></strong>.</p>
<p>There you have it, <code>boot = FALSE</code> and <code>robustSE = FALSE</code> is the way to go.</p>
</section>
<section id="issue-7-boundaries-of-the-confidence-intervals-are-rounded-differently" class="level2">
<h2 class="anchored" data-anchor-id="issue-7-boundaries-of-the-confidence-intervals-are-rounded-differently">Issue 7: Boundaries of the confidence intervals are rounded differently</h2>
<p>Did you notice? Each time we use <code>summary()</code> on a <code>mediate()</code> object, the lower boundary of the 95% CI is reported with 5 decimal places, while the upper boundary is reported with 2 decimal places. This also bothered Stack Overflow user sateayam over 4 years ago, and luckily user Roland <a href="https://stackoverflow.com/a/53852254">answered with a fix</a>:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">trace</span>(mediation<span class="sc">:::</span>print.summary.mediate, </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">at =</span> <span class="dv">11</span>,</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">tracer =</span> <span class="fu">quote</span>({</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>        printCoefmat <span class="ot">&lt;-</span> <span class="cf">function</span>(x, digits) {</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>          p <span class="ot">&lt;-</span> x[, <span class="dv">4</span>]</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>          x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%.6f"</span>, x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>          x[, <span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, p)</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">print</span>(x, <span class="at">quote =</span> <span class="cn">FALSE</span>, <span class="at">right =</span> <span class="cn">TRUE</span>)</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>        } </span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>      }),</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "print.summary.mediate"</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>mediation<span class="sc">:::</span><span class="fu">print.summary.mediate</span>(<span class="fu">summary</span>(med_6<span class="fl">.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value
ACME (control)           0.014773    -0.006472     0.042114    0.17
ACME (treated)           0.014018    -0.006213     0.041395    0.17
ADE (control)            0.028573    -0.088876     0.147886    0.66
ADE (treated)            0.027818    -0.084531     0.143331    0.66
Total Effect             0.042591    -0.073380     0.159502    0.48
Prop. Mediated (control) 0.159133    -2.467185     2.688134    0.56
Prop. Mediated (treated) 0.129613    -2.629199     2.783534    0.56
ACME (average)           0.014396    -0.006275     0.041930    0.17
ADE (average)            0.028196    -0.086757     0.144740    0.66
Prop. Mediated (average) 0.144373    -2.551698     2.761620    0.56

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">untrace</span>(mediation<span class="sc">:::</span>print.summary.mediate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Unfortunately, this solution also changes the way p-values are presented. Look again at the results from <code>med_6.5</code> and compare with the following:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">trace</span>(mediation<span class="sc">:::</span>print.summary.mediate, </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">at =</span> <span class="dv">11</span>,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">tracer =</span> <span class="fu">quote</span>({</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>        printCoefmat <span class="ot">&lt;-</span> <span class="cf">function</span>(x, digits) {</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>          p <span class="ot">&lt;-</span> x[, <span class="dv">4</span>]</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>          x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%.6f"</span>, x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>          x[, <span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, p)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">print</span>(x, <span class="at">quote =</span> <span class="cn">FALSE</span>, <span class="at">right =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>        } </span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>      }),</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "print.summary.mediate"</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>mediation<span class="sc">:::</span><span class="fu">print.summary.mediate</span>(<span class="fu">summary</span>(med_6<span class="fl">.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Causal Mediation Analysis 

Quasi-Bayesian Confidence Intervals

                         Estimate 95% CI Lower 95% CI Upper p-value
ACME (control)           0.015085     0.009936     0.020444    0.00
ACME (treated)           0.014097     0.009293     0.019127    0.00
ADE (control)            0.028259     0.014381     0.041851    0.00
ADE (treated)            0.027271     0.013905     0.040362    0.00
Total Effect             0.042356     0.027597     0.056765    0.00
Prop. Mediated (control) 0.355651     0.239774     0.526115    0.00
Prop. Mediated (treated) 0.332167     0.219000     0.507581    0.00
ACME (average)           0.014591     0.009622     0.019745    0.00
ADE (average)            0.027765     0.014143     0.041141    0.00
Prop. Mediated (average) 0.343909     0.229502     0.518043    0.00

Sample Size Used: 1955 


Simulations: 3000 </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">untrace</span>(mediation<span class="sc">:::</span>print.summary.mediate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The interim solution is to print the summary twice, once with the original function for expected p-value behavior, and another time with the edited function for confidence-interval consistency. Someone more well-versed might want to take a shot at adapting the code so that the behavior is maintained for the p-values<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> and fixed for the confidence intervals.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Previously called the “Fragile Families and Child Wellbeing Study”<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Another option, which we won’t go into, would be to take the responses to the items themselves and use a multi-level ordinal model with item as the random grouping factor.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Of course, the effects mentioned here are not really the effects of moving from X to Y on the mediator, but the mediated effect that changing from Race = “White” to Race = “Black” has on the probability of IPV <em>through its effect on the mediator</em>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Which Lumley apparently has also worked on!<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Perhaps taking into account user2554330’s <a href="https://stackoverflow.com/a/64830084">insight in another answer</a> about how p-values are stored and printed.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div quarto-reuse="quarto-reuse" class="quarto-appendix-contents"><a rel="license" href="https://creativecommons.org/licenses/by-nc/4.0/">https://creativecommons.org/licenses/by-nc/4.0/</a></div></section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{brazão2023,
  author = {Vasco Brazão and Vasco Brazão, Priya Devendran},
  title = {Adventures in Mediation Analysis with Weighted {GLMs}
    (Temporary Title)},
  date = {2023-01-01},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-brazão2023" class="csl-entry quarto-appendix-citeas" role="doc-biblioentry">
Vasco Brazão, and Vasco Brazão, Priya Devendran. 2023. <span>“Adventures
in Mediation Analysis with Weighted GLMs (Temporary Title).”</span>
January 1, 2023.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>