---
title: "How to Get Rich Quick (with Quips)"
subtitle: "Two poems, zero tips"
date: "2023-09-23"
categories: [poetry, english]
format: html
---

*First published on Medium for Bouncin' and Behavin' Poems ([link to original post](https://medium.com/the-bouncin-and-behavin-poetry-society/how-to-get-rich-quick-with-quips-d4dfc4c93e94?sk=a3ed6ccd3188ef3bda473a27f5b78833)).*

## **The Write-off**

I will not write about writing\
I will not write every day\
I will not pull you up the pyramid with me

If your strategy for earning is to write\
About your strategy for earning\
Then your strategy for earning is pretending that\
Your strategy for earning has any value\
At all

Spare me.

The author of *Rich Dad, Poor Dad* was a failed businessman\
Made rich by a book on how to get rich\
Then selling off his wisdom, saying\
— Look, I’ve made it,\
I must have known what I was doing

“Fraud” barely describes it\
“Grifter” — almost too kind\
“Kunk on Earth” is taken\
“Hustler” — he might not mind

In a wicked way, I respect it\
We all need money to survive\
The billionaires exploit,\
Celebrities lie,\
And writers beg for claps\
— For scraps\
To get by

So generate your articles\
On how to write your income\
Off you go on your readers’\
Fledgling reciprocity

I might write about writing\
I might think it’s not the same\
And yet — you’re here; I’m here\
Aren’t we both playing the game?

## **Snake-oil Limerick**

There once was a grifter named Ferris\
Who clearly could not feel embarrassed\
Said, “pay me a fine, and\
In four hours’ time\
You, too, can get rich from your terrace!”

He met up with veteran Bob\
Whose dad wasn’t really a slob\
They chatted all nice\
Upon their thrones of lies\
Deciding who next they might rob

In come our intrepid podcasters\
With ick, they exposed these disasters\
Bob’s book they dissected\
Then Tim’s they inspected\
— Slick houses built just out of plaster!

How powerless this relevation\
Against their entrenched reputation\
For so many dream of\
New wealth from quick schemes and\
Will pay their last dime for salvation

## **Some background for the curious**

The first poem is inspired by my experience in a group for Medium writers to share their stories and some of the complicated feelings that participating in it has brought up for me.

The second poem is particularly inspired by the episodes about *Rich Dad, Poor Dad* and *The 4-Hour Workweek* on the “If Books Could Kill” podcast (highly recommended!). I’m not sure why it had to come out as a limerick, but I assure you that it did.
