---
title: "O triângulo do vizinho"
subtitle: "(micro crónica)"
date: "2024-07-12"
categories: [portuguese]
format: html
---

*Publicado primeiro no Instagram a 12 de julho de 2024 ([link para post original](https://www.instagram.com/p/C9VT8ZcIZpt/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)).*

Um dos meus passatempos favoritos é remarcar "que belos cinquenta metros" num tom meio brincalhão meio professor azedo de quarta classe quando passamos carros infortunados que invariavelmente se sentem pouco protegidos pelo seu triângulo amigo, tão poucos passos foram dados antes da sua colocação. Não se passa muito tempo, mas passa-se-o bem. Quando vou acompanhado (ou a acompanhar), abre-se a esperança de ser recompensado por alguma locução, um "hum hum" ou "pois é " ou "são parvos" ou "esta gente" -- a última espelhando perfeita e deliciosamente o tom com o qual brotei a pequena interação, meio resmungão meio adulto emocionalmente atrapalhado ou porventura trapalhão. E assim se passa o tempo, encontrando pequenas luzes de conexão à sombra dos vistosos defeitos do vizinho onde os nossos se resguardam do sol e da atenção.
