---
title: "What if ADHD was the norm?"
subtitle: How might we describe "Neurotypical Spectrum Disorder" in a world where most people have ADHD?
date: "2023-02-21"
categories: [adhd, neurodiversity, english]
preview: "01_title.png"
---

| *This post is an adaptation / archive of something I first wrote for Instagram ([link to original post](https://www.instagram.com/p/CowlPXOrDDW/)). The images are reposted in order with respective image descriptions.*

TikTok account [\@myfavouritejo](https://www.tiktok.com/@myfavouritejo) (also on Instagram [\@myfavouritejo](https://www.instagram.com/myfavouritejo/)) asks: **what if neurodivergence was the norm?** Highly inspired by their content, I made this post to subvert how we generally conceive of Attention Deficit / Hyperactivity Disorder. If 95% of people were like that, would we create a diagnosis of "Neurotypical Spectrum Disorder"? What other characteristics come to mind?

![*Image text:\
How to Spot a Neurotypical - 5 Signs of Neurotypical Spectrum Disroder\
(POV: ADHD\* is the norm)\
\*Attention Deficit/Hyperactivity Disorder*](01_title.png){width="480"}

![*Image text:\
1. Lack of concentration\
Neurotypicals lack the normal ability to focus for hours and days on tasks that interest them. Often, they need to break up large goals into smaller steps that can be accomplished over weeks. This different kind of attention, also called "**hypofocus**", allows them to pay attention to **fewer things**, with **less intensity**, but **over a longer period of time** (days, weeks, months, even), which is why some people with NSD consider hypofocus a "superpower".*](02_point-1.png){width="480"}

![*Image text:\
2. Restricted interests*\
*It's common for neurotypicals to have **just a few interests over the course of their adult lives**. Even the few interests they have, they must enjoy moderately, **lacking the normal intensity**. Neurotypicals seem to prefer not to engage with their hobbies more than **once or twice a week**. Although this tendency hinders the normal development of a wide breadth of knowledge over the lifespan, people with NSD **can compensate for this deficit** by developing mastery in one or two domains.*](03_point-2.png){width="480"}

![*Image text:\
3. Slow learning rate\
Neurotypicals find it difficult to learn about topics that interest them with the speed that normal people are used to. **They prefer structured**, **slow** (think weeks, not days), **guided learning** to learn the same amount that a normal person could over a single weekend. If your neurotypical friend mentioned that they started learning how to crochet, don't expect to receive a sweater any time soon. **Be patient**, they'll get there, eventually.*](04_point-3.png){width="480"}

![*Image text:\
4. Atypical conversation patterns\
Likely due to **information processing difficulties**, neurotypical people tend to speak **slowly**, in a **monotone**, **without using speech modulation** (changing the speed and volume of speech, using varied accents, making random sounds) to have fun, express their enthusiasm, or express themselves more richly. They tend to only tell **one story at a time**, very linearly, prioritizing simplicity and depriving their conversation partners of highly interesting tangents.*](05_point-4.png){width="480"}

![*Image text:\
5. Low creativity\
People with Neurotypical Spectrum Disorder, despite saying they value creativity, suffer from a highly limiting belief: they believe in a "box" inside of which thinking occurs, and which contains a **very limited number of options**. They associate great discomfort with what they call "thinking outside of the box", meaning that their belief in this invisible box, irrational as it is, **has real consequences**, **restricting the ways they think and act in the world***.](06_point-5.png){width="480"}

![*Image text:\
People with adhd live in a world designed by and for neurotypical people.\
\
To navigate the world, they must learn how others act and pretend to be like them.\
\
What if neurotypicals learned more about adhd? what if we created a world that accommodates neurodiversity?*](07_end.png){width="480"}

| *Note: Colors are from this color palette, from Almodóvar's Pain and Glory: <https://www.kwanyuanliu.com/post/pain-glory-colors>*
