---
title: "Ideologia de género | Gender ideology"
date: "2023-09-08"
categories: [poetry, portuguese, english, gender]
format: html
---

*First published on Medium for Bouncin' and Behavin' Poems ([link to original post)](https://medium.com/the-bouncin-and-behavin-poetry-society/ideologia-de-g%C3%A9nero-gender-ideology-4a3ab75f9697?sk=83305e0fbceba73d8a70f868e26e4228). English translation below.*

Ideologia de género é rapazes de azul e meninas de rosa\
É biologia sem filosofia — quer dizer\
Nem biologia é\
É direitos do Homem\
É direito à depilação, não à transição\
É homens frágeis com medo dos maricas\
De ser maricas\
É medo da máscara emasculante\
Esconder mamas e mamilos\
Exibir todos os pelos\
É mulheres-polícia do que é ser mulher\
É forçar o mundo a adaptar-se à língua\
É prender quem só quer ser livre\
É esconder quem só quer ser viste

É absurdo\
É demagogo\
E enquanto perdura\
Só causa estrago\
Dor\
E embaraço

### **English Translation**

This is gender ideology: pink-clad girls and boys in blue\
Biology without philosophy — but, then…\
Not even biology\
It’s Men’s Rights\
The right to shave, but not transition\
Fragile men who fear the sissies\
Fear being a sissy\
Fear of the emasculating mask\
It’s hiding all the breasts and nipples\
While showing off your chest-grown follicles\
Policewomen policing womanhood\
Forcing the world to adapt to language\
Arresting them who just want freedom\
Hiding xem who just want to be seen

It’s absurd\
Deceitful dogma\
And while it lasts\
It only wrecks\
Hurts\
Embarrasses
